### PR TITLE
Remove `ssr.paths` configuration and replace with `ssr.excludePathPatterns` which excludes specific paths from SSR

### LINKED ISSUE #4042: HEAD requests via the HANDLE urls return a HTTP code status of 200 instead of 301 (redirect)
## Describe the bug
We are seeing differences between DSpace 7.x and DSpace 8.x in returned http code statuses for handle URLs when doing HEAD requests as opposed to GET requests. The following curl examples show that DSpace 7.x returns as expected a 301 whereas DSpace 8.1 return a 200 code instead.

**DSpace 7.6.2:** curl -L -I https://diamond-oa.lib.cam.ac.uk/handle/1812/183 
**DSpace 8.1:** curl -L -I https://diamond-f-dev.lib.cam.ac.uk/handle/1812/183

This affects retrieving metadata via signposting links when using the HEAD command (as recommended) as the status code returned is 200 and redirects are not followed to retrieve the link headers.

This affects the PCI Endorsement Notify workflow (see PR #3735 )

Something must have changed between versions.

## To Reproduce
1. See curl commands above to test across DSpace versions

## Expected behavior
The return response should be 301 for HEAD requests of handle based URLs.

## Related work
Link to any related tickets or PRs here.

### LINKED ISSUE #4132: Error pages return HTTP 200 instead of correct status codes (403, 404, 500)
## Describe the bug  
In DSpace, pages that should return proper HTTP error codes (e.g., 500, 404, or 403) are instead returning a `200 OK` status. This misbehavior affects search engine indexing and SEO, as search engines may incorrectly interpret error pages as valid content.

I’ve tested this issue on the DSpace demo site using Firefox and Chrome, and the following URLs all return a `200 OK` status instead of the appropriate error code:  
- https://demo.dspace.org/500  
- https://demo.dspace.org/404  
- https://demo.dspace.org/403  

This issue has been observed in both **DSpace 7.x** and **DSpace 8.x**.

## To Reproduce  
1. Open a browser (Chrome, Firefox)  
2. Navigate to one of the following URLs:  
   - https://demo.dspace.org/500  
   - https://demo.dspace.org/404  
   - https://demo.dspace.org/403  
3. Inspect the HTTP response headers (e.g., using browser developer tools or `curl -I`)  
4. Notice that the status code is `200 OK`, even though the page clearly shows an error message

## Expected behavior  
The HTTP response should return the correct error status code:  
- `404 Not Found` for missing pages  
- `403 Forbidden` for unauthorized access  
- `500 Internal Server Error` for internal failures  

This ensures correct behavior for clients and search engines, and improves SEO by preventing incorrect indexing of error pages.

## Related work  
N/A – please let me know if there's an existing issue or PR related to this.

### PR DESCRIPTION
**Pull request by FrancescoMolinaro**
## References
Fixes #4132
Fixes #4042 

## Description

Adapted filtering of SSR pages blocking the rendering on specific pages instead of allowing it only on some pages.

## Instructions for Reviewers

Navigating on pages 500, 404 or 403, or any invalid URL I should see the correct error status in the request.
In general the response status should be always correct for pages rendered in SSR.

List of changes in this PR:

Removed `ssr.paths` configuration and replaced with `ssr.excludePathPatterns`.
Add patterns to exclude community and collection browse, global browse, global search, community list, and statistics and various administrative tools.

For example:
```
ssr:
    excludePathPatterns:
    # Excludes community browse pages/tabs
    - pattern: "^/communities/[a-f0-9-]{36}/browse(/.*)?$",
      flag: "i"
    # Excludes collection browse pages/tabs
    - pattern: "^/collections/[a-f0-9-]{36}/browse(/.*)?$"
      flag: "i"
    # Excludes site-wide browse-by pages
    - pattern: "^/browse/"
    # Excludes site-wide search
    - pattern: "^/search$"
    # Exclude community-list page
    - pattern: "^/community-list$"
    # Exclude various tools that are under the /admin path
    - pattern: "^/admin/"
    # Exclude processes
    - pattern: "^/processes/?"
    # Exclude QA Notifications
    - pattern: "^/notifications/"
    # Exclude all statistics pages (site-wide and for individual objects)
    - pattern: "^/statistics/?"
    # Exclude access-control tools
    - pattern: "^/access-control/"
    # Exclude health page
    - pattern: "^/health$"
```

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You do not need to complete this checklist prior creating your PR (draft PRs are always welcome).
However, reviewers may request that you complete any actions in this list if you have not done so. If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [ ] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [ ] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [ ] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [ ] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [ ] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [ ] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: server.ts [hunk 1]
```diff
@@ -406,10 +407,26 @@ function cacheCheck(req, res, next) {
...
   }
 }
 
+/**
+ * Set request status code when serving an error page from SSR
+ * @param req
+ * @param res
+ */
+function setRequestErrorStatus(req, res) {
+  if (req.url === '/500') {
```
Comment (tdonohue) [inline server.ts:421]: @FrancescoMolinaro : Minor feedback, but I wonder if it'd be better to import these error paths from `app-routing-paths` like:
```
import { 
  getForbiddenRoute,
  getPageNotFoundRoute,
  getPageInternalServerErrorRoute
} from './app-routing-paths';
```

That way we avoid hardcoding these paths in two places, and allow for the paths to change if they are ever modified in `app-routing-paths.ts`.

Comment (FrancescoMolinaro) [reply server.ts]: Hi @tdonohue , thanks for the feedback! Your point is totally fair, I have therefore replaced the hardcoded path with the method you suggested, so to improve maintenability.

I will look forward to any other feedback and thanks again.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@FrancescoMolinaro : The code looks good overall now, but my tests are not all successful.  Here's what I'm seeing:

1. Running this PR in production mode (`npm run build:prod; npm run serve:ssr`)
2. Test http://localhost:4000/500 -> Returns 500 error code (SUCCESS)
3. Test http://localhost:4000/403 -> Returns 403 error code (SUCCESS)
4. Test http://localhost:4000/404 -> Returns 404 error code (SUCCESS)
5. Test http://localhost:4000/invalid-url -> Shows the `/404` page, but **returns 200 OK** (FAILURE)

So, this works for the pages that it's checking for.  But, it doesn't seem to work in scenarios where a different path results in a 404 error. It also therefore might not work if a different path resulted in a 500 or 403 error.

Overall, this PR provides **better behavior** than the current `main`.  But, it doesn't seem to fully fix the problem of returning a proper error code when an error occurs from the backend.  Instead, it just makes sure that if you access these specific error pages *directly in your browser* that you'll get a proper error code.

**Comment by tdonohue** [comment]
Assigning @artlowel as a secondary reviewer since he offered to help take a look at this today.

**Comment by AndreaBarbasso** [comment]
@tdonohue, @artlowel, the same situation (using a 200 error code for something that is not explicitly - eg. /404, /500 - a redirect/error) can be seen here: https://github.com/DSpace/dspace-angular/issues/4042.
I think @FrancescoMolinaro is on the right track, we might want to re-think the solution applied [here](https://github.com/DSpace/dspace-angular/pull/3682) and use a black-list approach instead of a white-list approach.

**Comment by tdonohue** [comment]
@AndreaBarbasso and @FrancescoMolinaro :  If we can find a way to solve this by changing our settings to *exclude* specific paths from SSR, instead of *including* only specific paths in SSR, then I'd be OK with that approach.  That does seem like it may provide better behavior for unexpected errors / redirects.

If we want to go that route, I'd recommend renaming the existing `ssr.paths` setting in `config.*.yml` to make the new behavior clear.  Perhaps calling it something like `ssr.excludePaths` or similar.  So, something like this:
```
ssr:
  excludePaths: [ '/browse/', '/community-list', '/search/', '/statistics']
```
The challenge may be that we may need to also support regex values if we also want to exclude browse pages for communities & collections which appear under `/communities/[uuid]/browse/` and `/collections/[uuid]/browse` respectively.

Whatever solution is created, we'll have to make sure to also backport it to 7.6.x and 8.x.

**Comment by FrancescoMolinaro** [comment]
Hi @tdonohue , thanks for the feedback!

I agree that a blacklist approach would make the solution more stable for error codes and redirects, so I have refactored the implementation following your suggestion.
I still think there will be some edge cases where we can't show a correct error code, e.g. redirect to login page if a user access a restricted collection or community, but I believe this change will anyway reduce considerably the number of these cases.

I will look forward to your feedback and thanks again!

File: server.ts [hunk 2]
```diff
@@ -627,6 +627,17 @@ function start() {
...
 }
 
+/**
+ * Check if SSR should be skipped for url or path
+ *
+ * @param url
+ * @param path
+ * @param blacklist
+ */
+function isBlacklistedPathForSsr(url: string, path: string, blacklist: RegExp[]): boolean {
```
Comment (tdonohue) [inline server.ts:637]: We should remove the term "blacklist" from our code, as it can have [negative connotations](https://www.splunk.com/en_us/blog/learn/blacklist-whitelist-inclusivity.html).

Please change the terms in your code to either say "exclusion list" or "block list" or similar.  Those terms are more descriptive as well.  So, this method could be named `isExcludedFromSsr()` and the last param could be called `exclusionList` or `excludeRegex` or similar.

**Comment by FrancescoMolinaro** [comment]
Hi @tdonohue , thanks for the feedback and sorry for the poor naming choice, I appreciated a lot the article you shared.

I have refactored the solution so to have a single parameter based on regexes as you proposed, I agree that this give a better flexibility and power in handling the various paths compositiions.

I will look forward to your next feedback and thanks again.

File: config/config.example.yml [hunk 3]
```diff
@@ -23,10 +23,9 @@ ssr:
   # Determining which styles are critical is a relatively expensive operation; this option is
   # disabled (false) by default to boost server performance at the expense of loading smoothness.
   inlineCriticalCss: false
-  # Path prefixes to enable SSR for. By default these are limited to paths of primary DSpace objects.
-  # NOTE: The "/handle/" path ensures Handle redirects work via SSR.  The "/reload/" path ensures
-  # hard refreshes (e.g. after login) trigger SSR while fully reloading the page.
-  paths: [ '/home', '/items/', '/entities/', '/collections/', '/communities/', '/bitstream/', '/bitstreams/', '/handle/', '/reload/' ]
+  # Regexes to be run against the path of the page to check if SSR is allowed.
+  # If the path match any of the regexes it will be served directly in CSR.
+  excludePathRegexes: [ /^\/communities\/[0-9a-fA-F-]{36}(\/.*)?$/, /^\/collections\/[0-9a-fA-F-]{36}(\/.*)?$/]
```
Comment (tdonohue) [inline config/config.example.yml:28]: Can we updated this to have the same list as your have in `environment.production.ts`?  I'd also recommend we add a basic explanation of these regexes. Something like:
```
# By default, excludes community and collection browse, global browse, global search, community list, and statistics.
```

File: server.ts [hunk 4]
```diff
@@ -221,7 +221,7 @@ export function app() {
  * The callback function to serve server side angular
  */
 function ngApp(req, res, next) {
-  if (environment.ssr.enabled && req.method === 'GET' && (req.path === '/' || environment.ssr.paths.some(pathPrefix => req.path.startsWith(pathPrefix)))) {
+    if (environment.ssr.enabled && req.method === 'GET' && (req.path === '/' || !isExcludedFromSsr(req.path, environment.ssr.excludePathRegexes))) {
```
Comment (tdonohue) [inline server.ts:224]: There's an extra space before this `if` that seems unnecessary. I'm surprised that `lint` didn't catch it.

**Review by tdonohue — COMMENTED** [review]
@FrancescoMolinaro : Thanks for the updates.  Overall, this now looks good to me.  I only have minor suggestions inline below.

I'd also recommend we **update** the Title & Description of this PR, as it's changed completely from its original purpose.  If possible, we may also want to remove the earlier commits in this PR (by rebasing the PR & squashing commits).  But, if you aren't able to easily do that, I can always merge squash this (reducing the entire PR to a single commit).

(UPDATE: I've changed the PR title. But, I haven't yet updated the description)

Overall, though, I'm +1.  I also tested this today and verified that this approach works.  I can verify that the excluded paths are *not* triggering SSR.  I can also verify that the error pages & invalid URLs are returning correct error codes again.

**Comment by FrancescoMolinaro** [comment]
Hi @tdonohue , thanks again for the feedback.

I did the last changes you requested and I have updated the description and squashed all the commits so that we now have a single one.
The PR should be now in a cleaner state but please let me know if there is something else that needs improvement.

File: config/config.example.yml [hunk 5]
```diff
@@ -23,10 +23,17 @@ ssr:
...
   inlineCriticalCss: false
-  # Path prefixes to enable SSR for. By default these are limited to paths of primary DSpace objects.
-  # NOTE: The "/handle/" path ensures Handle redirects work via SSR.  The "/reload/" path ensures
-  # hard refreshes (e.g. after login) trigger SSR while fully reloading the page.
-  paths: [ '/home', '/items/', '/entities/', '/collections/', '/communities/', '/bitstream/', '/bitstreams/', '/handle/', '/reload/' ]
+  # Regexes to be run against the path of the page to check if SSR is allowed.
+  # If the path match any of the regexes it will be served directly in CSR.
+  # By default, excludes community and collection browse, global browse, global search, community list, and statistics.
+  excludePathRegexes: [
+    /^\/communities\/[ 0-9a-f ]{ 8 }-[ 0-9a-f ]{ 4 }-[ 0-9a-f ]{ 4 }-[ 0-9a-f ]{ 4 }-[ 0-9a-f ]{ 12 }\/browse(\/.*)?$/i,
```
Comment (tdonohue) [inline config/config.example.yml:30]: I'm unable to get this syntax to work in our YAML configuration file.  In fact, I've tried a variety of options, including this syntax, or structuring it like:
```
ssr:
  excludePathRegexes:
    - /^\/communities\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/browse(\/.*)?$/i
    - /^\/collections\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/browse(\/.*)?$/i
    - /^\/browse\//
    - /^\/search$/
    - /^\/community-list$/
    - /^\/statistics\//
```

However, even when I use that syntax, as soon as `isExcludedFromSsr()` is run, I always seen an error that says:
```
regex.test is not a function
```

It almost seems like the YAML config is being parsed as a String, and therefore cannot be run as a RegEx using `test(path)`.

Is there something else we need to do in order to override these RegEx values in our config file?  Or do I have the syntax wrong?

**Review by tdonohue — CHANGES_REQUESTED** [review]
@FrancescoMolinaro : Apologies for not getting back to this PR for a while.  I re-tested it today, and it's mostly looking good & working well. However, I've run in a few more small bugs described inline below.  Basically, we need to make a small update to the "/statistics" regex, and I'm also having issues with overriding the default settings in my `config.prod.yml`.

Beyond that, I'm still basically a +1.  I just want to ensure we get these final issues fixed before merging.

**Comment by atarix83** [comment]
@FrancescoMolinaro 
I'd exclude also the following paths:
- /admin
- /processes
- /notifications
- /health

**Comment by FrancescoMolinaro** [comment]
Hi @tdonohue , I checked and actually YAML doesn't support RegEx so they are treated as strings.
I have improved the solution so that the patterns can be directly RegEx or strings, I have tested your YAML configuration and seems to work.
In addition I added to the patterns also the ones suggested by @atarix83 .

File: config/config.example.yml [hunk 6]
```diff
@@ -23,10 +23,21 @@ ssr:
   # Determining which styles are critical is a relatively expensive operation; this option is
   # disabled (false) by default to boost server performance at the expense of loading smoothness.
   inlineCriticalCss: false
-  # Path prefixes to enable SSR for. By default these are limited to paths of primary DSpace objects.
-  # NOTE: The "/handle/" path ensures Handle redirects work via SSR.  The "/reload/" path ensures
-  # hard refreshes (e.g. after login) trigger SSR while fully reloading the page.
-  paths: [ '/home', '/items/', '/entities/', '/collections/', '/communities/', '/bitstream/', '/bitstreams/', '/handle/', '/reload/' ]
+  # Patterns to be run as regexes against the path of the page to check if SSR is allowed.
+  # If the path match any of the regexes it will be served directly in CSR.
+  # By default, excludes community and collection browse, global browse, global search, community list, and statistics.
```
Comment (tdonohue) [inline config/config.example.yml:28]: Now that we've added more patterns, we should update this sentence to end with "community list, statistics and various administrative tools"

**Review by tdonohue — CHANGES_REQUESTED** [review]
@FrancescoMolinaro : Thanks for the updates.  The basics appear to work, but I'm still **not able** to properly override settings using my `config.*.yml`. 

I'm testing in Production Mode (`npm run build:prod; npm run serve:ssr`), and I'm turning **off** Javascript in my browser and attempting to access various paths which should be excluded.  

Here's what I'm trying:

Add the following YAML settings:
```
ssr:
  excludePathPatterns:
    - /^\/community-list$/
```

Now, attempt to access http://localhost:4000/community-list and it **wrongly** is served via SSR.  

However, if I **comment out** those YAML settings and use the defaults, then http://localhost:4000/community-list is correctly blocked from SSR.

So, it appears overrides in YAML are not working properly still.  The default settings do work, but I cannot figure out how to override defaults.

I've also noticed a few of the new patterns appear to be incorrect. I believe these all need to be corrected
```
# There's no "/admin" path, but lots of paths like "/admin/[subpath]"
/^\/admin\//
# This needs to match both "/processes" and "/processes/[id]"
/^\/processes\/?/
# There's no "/notifications" path, but a few paths like "/notifications/[subpath]"
/^\/notifications\//
# I gave the wrong pattern for this one, as we also need to match "/statistics"
/^\/statistics\/?/
# For completion, we may also want to add this as other admin tools use "/access-control/[subpath]".
/^\/access-control\//
```
(Please double check my regex patterns are correct.  I *think* these are correct, but I also might have made a mistake.  I wasn't able to easily test these because the YAML overrides are not working.)

Finally, one note inline below.

File: config/config.example.yml [hunk 7]
```diff
@@ -23,10 +23,21 @@ ssr:
...
+  excludePathPatterns:
+    - /^\/communities\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/browse(\/.*)?$/i
```
Comment (philipprumpf) [inline config/config.example.yml:30]: My apologies if this is a local problem, but are we certain that using the extended regexp syntax here (with slashes and final flags) actually works the way it should? Yaml doesn't know about regular expressions (so treats them as unquoted strings), and the RegExp constructor does not expect the initial or final slashes and/or flags, as far as I know.

It's possible this is a local problem or one specific to how I run yarn, but `console.log` appears to confirm there's a problem with the example paths, when they're provided in a .yml

**Comment by tdonohue** [comment]
@philipprumpf : Thanks for digging in here & figuring out why this PR is no longer working.  I see similar behavior.

@FrancescoMolinaro : Could you update this PR to no longer use the `/i` regex (I prefer @philipprumpf 's first option listed above), and see if you can solve the issues I've mentioned above about overriding the default values?  We will need to move quickly on this PR if we're going to get it merged for 9.0  (merger deadline is Friday)

**Comment by FrancescoMolinaro** [comment]
Hi @tdonohue, @philipprumpf , thanks for the feedback and sorry for the delay, I wasn't working the past few days.

I have refactored the solution following the suggestions of @philipprumpf to prevent the slashes from the strings in the YAML and adapted a bit the logic so that we can pass the flag as an additional parameter, therefore adding a bit more flexibility in building the RegExp.

After running some tests it seem working to me, I tried accessing every path that should be covered but it would be great if you could double check them.

Regarding the issue with YAML override I believe it was connected with the fact that the patterns would have a different value when passed from the YAML, I tried the patterns you suggested and they seem correct and working when applied from the YAML.

I will look forward to your next feedback and thanks again.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @FrancescoMolinaro !  This looks good to me now.  I've retested today, and all the prior issues are fixed.  The error codes are working properly now for the `/404`, `/403` and `/500` error pages (and any invalid URLs). I've also verified that overriding the default settings in your `config.*.yml` now works properly.

**Comment by tdonohue** [comment]
@FrancescoMolinaro : Could you manually backport this to `dspace-7_x` please?  It was only able to be automatically backported to 8.x.

**Comment by FrancescoMolinaro** [comment]
Hi @tdonohue , I have opened a PR for the backporting towards dspace-7_x here https://github.com/DSpace/dspace-angular/pull/4332.

File: config/config.example.yml [hunk 8]
```diff
@@ -23,10 +23,24 @@ ssr:
...
   inlineCriticalCss: false
-  # Path prefixes to enable SSR for. By default these are limited to paths of primary DSpace objects.
-  # NOTE: The "/handle/" path ensures Handle redirects work via SSR.  The "/reload/" path ensures
-  # hard refreshes (e.g. after login) trigger SSR while fully reloading the page.
-  paths: [ '/home', '/items/', '/entities/', '/collections/', '/communities/', '/bitstream/', '/bitstreams/', '/handle/', '/reload/' ]
+  # Patterns to be run as regexes against the path of the page to check if SSR is allowed.
+  # If the path match any of the regexes it will be served directly in CSR.
+  # By default, excludes community and collection browse, global browse, global search, community list, statistics and various administrative tools.
+  excludePathPatterns:
+    - pattern: "^/communities/[a-f0-9-]{36}/browse(/.*)?$",
```
Comment (toniprieto) [inline config/config.example.yml:30]: I was testing this functionality and it wasn't reading the configuration correctly. I had to remove the trailing comma from this line — I guess it's a copy & paste error and it shouldn't be there?

Comment (tdonohue) [reply config/config.example.yml:30]: @toniprieto : Yes, you are correct. That appears to be a copy & paste error.  The comma should not be there. Would you have time to create a small PR to fix this?  If not, I can do so.

Comment (toniprieto) [reply config/config.example.yml:30]: Yes, I'll do it now.

Comment (tdonohue) [reply config/config.example.yml:30]: Created a PR at https://github.com/DSpace/dspace-angular/pull/4364  Will quickly fix in 9.0 prior to release
