### PR TITLE
Fix pagination in metadata browse links

### LINKED ISSUE #1713: Browse menus on top must reset pagenumber to 1 when a link clicked.
**Describe the bug**
On browse search results, if you click a link with a big number of results no item is shown in the opening page. This is because the page parameter in the url (bbm.page) is not reset. The new page tries to show the Page number of the previous page.

**To Reproduce**
1. Open Ds7 demo site https://demo7.dspace.org/home
2. Click Browse by Author link at the top menu https://demo7.dspace.org/browse/author
3. Navigate to page 110 https://demo7.dspace.org/browse/author?bbm.page=110
4. Click on Simmons, Cameron which have 189 items https://demo7.dspace.org/browse/author?bbm.page=110&value=Simmons,%20Cameron
5. You see that a blank page loads. https://demo7.dspace.org/browse/author?bbm.page=96&value=Simmons,%20Cameron
6. Check that the page parameter in the url that it still tries to show page 110, which is in fact the number of previous page
7. Change the url parameter bbm.page to 1. Observe that correct result is shown.
**Expected behavior**
When a link clicked at step 4 above, a second parameter for page number must be used. And that parameter must start by 1.
The bbm.page parameter must be kept in the memory. If the user clicks "All browse results" button anytime during his navigation of the author's related works, than the system must go back to the  previous bbm.page (110) at step 3. 
This way the user can continue browsing by authors, from the point he/she forked to the author.
**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by LotteHofstede**
## References
* Fixes #1713
* Fixes https://github.com/DSpace/DSpace/issues/8470

## Description
This PR solves the issue where when clicking a browse entry, the current page is incorrectly transferred to the page you clicked.
It also makes sure that when you click the '**<-- All browse results**', you are returned to the same page number as where you originally were redirected from.

## Instructions for Reviewers
Using `api7.dspace.org` backend, visit `[dspace]/browse/author?bbm.page=112` .
Scroll down and click browse entry '**Simmons, Cameron**'.
This should redirect you to the **first** page of this author's articles: the pagination buttons at the bottom should show that you are on the first page.

Clicking '**<-- All browse results**' should send you back to the 112th page of the author browse-by pages: `[dspace]/browse/author?bbm.page=112`

  

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).

### CODE REVIEW

File: src/app/shared/browse-by/browse-by.component.ts [hunk 1]
```diff
@@ -1,17 +1,18 @@
...
-import { combineLatest as observableCombineLatest, Observable } from 'rxjs';
+import { BehaviorSubject, combineLatest as observableCombineLatest, Observable, Subscription } from 'rxjs';
 import { ListableObject } from '../object-collection/shared/listable-object.model';
 import { getStartsWithComponent, StartsWithType } from '../starts-with/starts-with-decorator';
 import { PaginationService } from '../../core/pagination/pagination.service';
 import { ViewMode } from '../../core/shared/view-mode.model';
 import { RouteService } from '../../core/services/route.service';
 import { map } from 'rxjs/operators';
 import { hasValue } from '../empty.util';
+import { BBM_PAGINATION_ID } from '../../browse-by/browse-by-metadata-page/browse-by-metadata-page.component';
```
Comment (tdonohue) [inline src/app/shared/browse-by/browse-by.component.ts:15]: This import appears to be unused (and LGTM complains about it above)

**Review by tdonohue — APPROVED** [review]
👍 Thanks @LotteHofstede !  I gave this a test today and verified that it fixes #1713.  It also fixes a similarly reported issue with Browse by Subject https://github.com/DSpace/DSpace/issues/8470 (I'll link this PR up to that issue as well).

So, I'm +1 this change.  That said, there's a very minor LGTM warning in this PR..so, it'd be nice if you could quickly clean that up before we merge it (see inline comment below).

**Comment by tdonohue** [comment]
Thanks @LotteHofstede !  This looks good now. Merging immediately.
