### PR TITLE
Reduce browse definition requests on simple item page

### LINKED ISSUE #3700: Excessive number of browse definition request on simple item page.
## Describe the bug
Each `ItemPageFieldComponent` performs a separate request to obtain potential browse indexes for the relevant metadata its relevant metadata fields.

## To Reproduce
Go to a simple item page for an item with enough metadata to spawn multiple `ItemPageFieldComponent`s.
In the browser's network log, observe the repeated GET requests to the `http://localhost:8080/server/api/discover/browses/search/byFields?fields=...` endpoint.
This slows down the page.

## Expected behavior
Since all this information has already been requested for the "All of DSpace" navbar menu, we should be able to retrieve this information from the cache, rather than re-requesting it.

## Related work
#3701

### PR DESCRIPTION
**Pull request by KoenP**
## References
* Fixes #3700

## Description
Current behavior: each `ItemPageFieldComponent` on a simple item page sends a request to retrieve the relevant browse definition.
New behavior: each `ItemPageFieldComponent` retrieves the list of all browse definitions from the cache (which has already been requested for the navbar) and searches for the relevant browse definition.

### List of changes in this PR
* `ItemPageFieldComponent.browseDefinition` modified to retrieve all browse definitions by invoking `browseService.getBrowseDefinitions()`, and then finding the relevant browse definition.
* `BrowseDefinition` and subclasses modified to have the `metadataKeys` field in `BrowseDefinition`, rather than in its subclasses.

### Reproducing pre-PR behavior
Open a simple item page and observe that that several requests are being made to `/server/api/discover/browses/search/byFields`.

### Testing the PR
Open a simple item page and observe that only one request is made to `/server/api/discover/browses`, and that the behavior of the page is otherwise unchanged.

## Checklist
- [x] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [x] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts [hunk 1]
```diff
@@ -74,9 +84,26 @@ export class ItemPageFieldComponent {
...
+        mergeAll(),
+        filter((def: BrowseDefinition) =>
+          intersectionWith(def.metadataKeys, this.fields, ItemPageFieldComponent.fieldMatch).length > 0,
+        ),
+        take(1),
       );
     }
+
+    /**
+     * Returns true iff the spec and field match.
```
Comment (nwoodward) [inline src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts:100]: Typo: "iff" => "if"

**Review by nwoodward — APPROVED** [review]
Thanks @KoenP! I tested this PR locally using items with lots of metadata, and it reduced the calls to "http://localhost:8080/server/api/discover/browses/search/byFields?field=" from many down to one.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @KoenP !  I tested this today and verified it fixes the bug.  Now I'm only seeing a single browse definition request on Item pages (when there sometimes could be many)

File: src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts (hunk 1 above)
Comment (nwoodward) [reply src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts:100]: Ah, yeah. That makes sense.
