### PR TITLE
Fix for User profile (/profile): only 20 group memberships shown instead of all

### LINKED ISSUE #2357: User profile (/profile): only 20 group memberships shown instead of all
**Describe the bug**
Instead of the full list of user groups, only the first 20 seem to be shown on the user profile, in a non-pageable list.
I saw this on 7.4 and did not re-test or reproduce this problem in 7.6 for the time being.

**To Reproduce**
1. Login as an EPerson who is member of over 20 groups
2. Go to to /profile and scroll to the bottom to see the list of groups

**Expected behavior**
The full list of groups should be visible, preferably pageable.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by VictorHugoDuranS**
Hi @tdonohue , I'm @jtimal partner, I like to share this PR with you:

## References
* Fixes #2357

## Description
Set pagination on groups of the user on  profile page

## Instructions for Reviewers
On the profile page I added the pagination of groups adding the pagination template and modifying the current service of groups for paginated it. I set 20 elements par page as default in the pagination

List of changes in this PR:
* I created a default variable for group pagination
* I changed the template of group list adding the pagination template
* I added the 'PaginationService' for get the current page in the pagination 
* I changed the current services for get groups of the user adding 'Pagination Service' and add the option for paginate the groups, so  the  pagination component change the current page update the results

Example:

image

image

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: src/app/profile-page/profile-page.component.ts [hunk 1]
```diff
@@ -99,7 +111,17 @@ export class ProfilePageComponent implements OnInit {
...
     );
-    this.groupsRD$ = this.user$.pipe(switchMap((user: EPerson) => user.groups));
+    this.groupsRD$ = this.paginationService.getCurrentPagination(this.optionsGroupsPagination.id, this.optionsGroupsPagination).pipe(
+      switchMap((pageOptions: PaginationComponentOptions) => {
+        return this.epersonService.findById(this.currentUser.id, true, true, followLink('groups',{findListOptions: {
+            elementsPerPage: pageOptions.pageSize,
+            currentPage: pageOptions.currentPage
+          }}));
+      }),
+      getAllSucceededRemoteData(),
```
Comment (artlowel) [inline src/app/profile-page/profile-page.component.ts:121]: it would be good to use getAllCompletedRemoteData here, and deal with the case when the request fails as well (e.g. show an error notification), or even better: don't filter on RemoteData status at all to deal with the case where it is loading too (e.g. show a loading component)

**Review by tdonohue — CHANGES_REQUESTED** [review]
@VictorHugoDuranS : Thanks!  We also reviewed this PR together as a team in our DSpace Developer Meeting.  The feedback here is similar.  We need to have a PR created against `main` so that we can apply these changes to 8.x and 9.0.   Overall, though, the code looks reasonable (except for the one note by @artlowel above).  

We didn't get a chance to test this, but I'll volunteer to help test it (if no one else gets to it) once we have a version of this PR against the `main` branch

File: src/app/profile-page/profile-page.component.ts (hunk 1 above)
Comment (VictorDuranEscire) [reply src/app/profile-page/profile-page.component.ts]: @artlowel  I changed getAllSucceededRemoteData for getAllCompletedRemoteData function

**Comment by VictorDuranEscire** [comment]
@tdonohue I merged the main branch to this branch with the current changes. Thanks for the feedback!. 
I will be waiting for your response

File: src/app/profile-page/profile-page.component.ts (hunk 1 above)
Comment (artlowel) [reply src/app/profile-page/profile-page.component.ts]: Thanks!

**Review by tdonohue — CHANGES_REQUESTED** [review]
@VictorHugoDuranS : Apologies for the delay in reviewing this again.  I tested this today, and the basic functionality *works*, but I'm seeing a number of errors in my brower's DevTools  anytime I visit the `/profiles` page.  These seem to be caused by the new code.

Here's what I'm doing:
* Install this PR and run in production mode (`npm install; npm run build:prod; npm run serve:ssr`)
* Open Chrome DevTools and visit the site.
* Login and visit the `/profiles` page.  In my Chrome DevTools "Console", I see these errors logged:
    * `Error TypeError: Cannot read properties of null (reading 'isLoading')`
    * `Error TypeError: Cannot read properties of undefined (reading 'createComponent')`
* Neither of the above errors occur on https://sandbox.dspace.org, or if I run the frontend **without** this PR installed.  That implies these errors are based on the code in this PR.

Beyond that, the pagination is working for me.  So, this can be merged once the errors are fixed.

(As a sidenote, you do not need to modify **every** json5 file in the future, when you add a new translation key.  It's only necessary to modify the "en.json5" file, and the others will be updated the next time they are retranslated.)

**Comment by VictorDuranEscire** [comment]
Hi @tdonohue , I made the corrections to address the remarks you mentioned in a previous comment, I also updated the translations to leave only English.

File: src/assets/i18n/ca.json5 [hunk 2]
```diff
@@ -2558,6 +2558,7 @@
   // "error.objects": "Error fetching objects",
   "error.objects": "Error en recuperar objectes",
 
+
```
Comment (tdonohue) [inline src/assets/i18n/ca.json5:2561]: Same here and for every other file *except* the `en.json5` file.  You should remove the unnecessary blank lines.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@VictorHugoDuranS and @VictorDuranEscire :  This is looking better.  The bugs are fixed.  However, this PR is still modifying **every single *.json5** file by adding in unnecessary blank lines.  Please remove those unnecessary changes from this PR, as they can make the PR *much more difficult* to backport to 8.x and 7.x.   

Ideally, your PRs should be as small as possible without making any unnecessary formatting changes, etc.  Thanks!

**Comment by VictorDuranEscire** [comment]
Hi @tdonohue , thanks for the feedback, I made the adjustments to remove the changes to the .json5 files only leaving the English translation. I will consider these comments in my future PRs.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @VictorHugoDuranS !  This now looks good to me.  Merging and porting to 8.x & 7.x
