### PR TITLE
Common Extendend Regex format for submission-forms

### LINKED ISSUE #1950: Common Extendend Regex format for submission-forms
**Describe the bug**
As of now, because the same field (`regex`) is shared between `Java` and `JS/TS` languages you can't use a common flag format to make it work for both.
As an example, if you choose the _Java inline flag format_ your regular expression will be: `(?i)[a-z]+`
> This expression will search for a word made of characters between `a` and `z` in upper or lower case (i flag means `case insensitive`).
With this regex the `REST` part will work as expected, but the `anglular` one will not recognize this syntax.
- The String `hello`:
  - will be recognized valid by the `angular` part;
  - will be recognized valid by the `REST` part.
- The String `123`:
  - will be recognized valid by the `angular` part;
  - won't be recognized valid by the `REST` part.

> The `angular` part can have unexpected behavior, because the string `(?i)[a-z]+` is not a valid `RegExp`, and will throw an exception during the creation phase.

Similarly, if you choose the ECMAscript format: `/[a-z]+/i`.
- The String `hello`:
  - won't be recognized valid by the `angular` part;
  - won't be recognized valid by the `REST` part.
- The String `/hello/i`:
  - will be **wrongly** recognized valid by the `angular` part;
  - will be **wrongly** recognized valid by the `REST` part.

The baddest news is that `/hello/i` could have been successfully saved in DSpace, and for the String `hello` the red input-box will have a red border and a validation message will be shown saying that: _**the value is not valid for the regex**_ `/[a-z]+/i`.
The user could misunderstand this message, because the string 'hello' will be valid for the format `/[a-z]+/i` inside a regex-tester, and because we are in ECMAScript-domain this should be valid.

The solution could be use of the standard ECMAScript `/{regex}/{flag}` recognize it and split it into two parts, using them correctly to create `RegExp`. And also use this format `/{regex}/flag` as part of validation message for the user (because we show it inside the `angular` part, and I think is easily understandable, the other format could led to misunderstanding because of `?` that is also the lookaround hook).

**To Reproduce**
Insert some regex with flags /{regex}/{flags} inside input-forms definition file, or insert a regex with / as delimiter: /{regex}/. This could led to wrong / unexpected behaviors.

**Expected behavior**
We should use the extended definition for regex, that will support all of these cases:

/{regex}/{flags}
/{regex}/
{regex}
In this way we could easily parse and compute the right pattern with or without flags, and also check that the regex field contains a valid pattern.

**Related work**
Linked to this `Backend` issue: https://github.com/DSpace/DSpace/issues/8563

### PR DESCRIPTION
**Pull request by vins01-4science**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #1950
* Requires DSpace/DSpace#8565

## Description
As of now Angular field validation uses the common ECMAScript format.
The configured regex for the field will be parsed and splitted for flags.

## Instructions for Reviewers
You'll need to configure a proper regex for a field inside a submission-form, the format should be `/{regex}/{flags}`.
Once configured, the field will be properly validated whenever changed / saved inside the correlated form.
If the field doesn't match the configured pattern an alert message will be shown.

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

File: src/app/shared/form/builder/parsers/field-parser.ts [hunk 1]
```diff
@@ -344,7 +346,13 @@ export abstract class FieldParser {
   }
 
   protected addPatternValidator(controlModel) {
-    const regex = new RegExp(this.configData.input.regex);
+    const validatorMatcher = this.configData.input.regex.match(REGEX_FIELD_VALIDATOR);
```
Comment (tdonohue) [inline src/app/shared/form/builder/parsers/field-parser.ts:349]: Can we add some comments here to describe what this is validating?   Currently, this code is hard to read/understand because it is not clear what the `REGEX_FIELD_VALIDATOR` is doing.   It's very important to add comments to complex regex so that developers understand their purpose.

Alternatively, you could add some specs which prove that this validator is working as expected.

**Review by tdonohue — COMMENTED** [review]
@vins01-4science : Gave this a test / review today & it seems to be working. However, I'd appreciate it if you could better comment your code and/or add specs.  More inline below. 

So, overall, I'm +1 here, but I'd appreciate some minor code improvements.

**Comment by vins01-4science** [comment]
@tdonohue: thank you for the review.

New tests and comments have been added to clarify the behavior of the new code changes.
I hope that's all good now :+1: 

Thank you!

**Review by tdonohue — APPROVED** [review]
👍 Thanks @vins01-4science !  The new code comments and tests look good to me.  So, this is ready to go as well.  I'll merge both PRs shortly.
