### PR TITLE
Submission dropzone issues

### LINKED ISSUE #849: Uploading a file on Submission Form always brings you to the top of the page
**Describe the bug**
When filling out the Submission Form, anytime you drag and drop a file onto the form, you are auto-scrolled back to the top of the page.  This can be frustrating.  

For example, if you drag & drop a new file into the "Upload files" section of the submission page (which appears near the bottom of the page), you are scrolled to the top while the file uploads.  Then you have to scroll all the way back down to the bottom in order to complete your submission.

**To Reproduce**
1. Start a new submission
2. Fill out metadata in "Describe" sections
3. Once you get to the "Upload file" section, drag & drop a file onto the page.
4. You will be scrolled to the top again.  In order to complete the submission (or see info about the uploaded file) you'll have to scroll back down.

**Expected behavior**
I expect that a drag & drop of a file should not change your position on the page.  Instead, you should see the file upload progress bar regardless of where you are on the page.  So, if you drag & drop while looking at the "Upload file" section, that progress bar should either appear in that section or as a popup modal (like the successful or error messages).

### LINKED ISSUE #957: Upload dropzone is shown in the submission if there's no upload section
**Describe the bug**
If you configure a submission without an upload section, the upload drop zone at the top of the page is still shown.

**To Reproduce**
1. Configure a collection without an upload section in the submission
2. Authenticate in the UI
3. Submit an item to that collection
4. Verify that you can still see the drop zone.

**Expected behavior**
I'd expect the upload drop zone only to be visible if the submission has an upload section

### PR DESCRIPTION
**Pull request by LotteHofstede**
## References
* Fixes #957
* Fixes #849

## Description
- The dropzone on the submission form will no longer be rendered when the submission form does not include an upload section.
- When a file is dropped on the submission forms dropzone, the page will not automatically scroll to the top of the age anymore. The dropzone and its progress bar is now always visible at the top of the page, similar to the collection dropdown.  

## Instructions for Reviewers
- Collections without an upload section in their form definition, should no longer show the dropzone on their submission page
- Dropping a file anywhere on the submission page should no longer cause the page to scroll up, but should always show the progress bar at the top of the page, independently from the user's current scroll position.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).

### CODE REVIEW

File: src/app/submission/form/submission-form.component.ts [hunk 1]
```diff
@@ -128,7 +135,11 @@ export class SubmissionFormComponent implements OnChanges, OnDestroy {
           } else {
             return observableOf([]);
           }
-        }));
+        }),
+        tap((sectionList) => {
+          this.uploadEnabled$.next(isNotEmpty(sectionList) && sectionList.some(config => config.sectionType === SectionsType.Upload));
```
Comment (atarix83) [inline src/app/submission/form/submission-form.component.ts:140]: In my opinion a cleanest way to find out if the upload section is available is to use the [sections.service](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/sections/sections.service.ts). it includes a [method to check the availability of a section by given id](https://github.com/DSpace/dspace-angular/blob/ea3886bbfa63d8bc41664f3d76d0534863faceac/src/app/submission/sections/sections.service.ts#L303-L310). It'd would be nice to have a similar method that use the section type to check if any sections with the given type are available

**Review by atarix83 — CHANGES_REQUESTED** [review]
thanks @LotteHofstede for the PR. I've tested and it seems to work properly. However I have a suggestion on implementation which it would be nice to be implemented

**Review by tdonohue — APPROVED** [review]
👍 Looks good to me & tested and it works.

I've also verified that @atarix83's feedback was addressed in this PR, using the recommended method he linked to.

**Review by atarix83 — APPROVED** [review]
@LotteHofstede the changes you made is not exactly what I meant. Indeed using the `isSectionAvailable` to check if upload section is available works only because by rest configuration currently the upload section's type and the id are the same : 
``` 
        <step-definition id="upload">
            <heading>submit.progressbar.upload</heading>
            <processing-class>org.dspace.app.rest.submit.step.UploadStep</processing-class>
            <type>upload</type>
        </step-definition>
```
A better solution is to create a similar method that search by section type, so we would be safe id the id will be changed. I've applied this change [with this commit](https://github.com/4Science/dspace-angular/commit/d28e9c5c2fb1c4841261fd73c02512a2fc5146c0).
 @tdonohue My suggestion is to pick it up and to merge this PR after a quick review

**Comment by LotteHofstede** [comment]
@atarix83 Thanks for the feedback. You're absolutely right, I'm sorry I missed that. I cherry-picked your changes into this branch and pushed them.

**Comment by tdonohue** [comment]
Merging, as this is at +2 & @atarix83's improvement commit was included. Thanks again @LotteHofstede (and @atarix83) !

**Comment by tdonohue** [comment]
Unfortunately, after merging this I've just now realized it's had major side effects. It's now impossible to click on any field in the submission form, which means it's impossible to submit a new item.  I've created a revert PR #1083 which I'll merge shortly just to get the demo site working again.

**Comment by LotteHofstede** [comment]
@tdonohue That's indeed unfortunate, my apologies for not noticing this very obvious issue.

It should be fixed now that the page-wide dropzone is only rendered once the user actually drags a file onto the window.

I created a new PR https://github.com/DSpace/dspace-angular/pull/1087
