### PR TITLE
Use keyboard to select values

### LINKED ISSUE #2500: Can't use keyboard to select value in submission form dropdown
**Describe the bug**
When using the `dropdown` input type in the DSpace 7.6 submission form, it is not possible to jump to a value in the list by typing a letter. For example, I want to jump to the `Journal Article` value by pressing the letter "j" or "J":

https://github.com/DSpace/dspace-angular/assets/191754/bd9ec773-688f-4df2-8581-7ecfe6c3f101

**To Reproduce**
1. Configure a field in the submission form to use a `dropdown` type with a value pairs, for example the types.
2. Try to type a letter to jump to an item in the list

**Expected behavior**
Being able to navigate the dropdown using the keyboard is a feature of native HTML `<select>` elements in browsers (see [MDN docs with example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)).

In DSpace 6 the `dropdown` type actually presents as a list, but we can navigate the list using the keyboard:

https://github.com/DSpace/dspace-angular/assets/191754/7c398ac8-ec65-499f-88e3-0fb07daea31e

### LINKED ISSUE #2805: Submission dropdowns do not load previously selected and saved value after reload
**Describe the bug**
Component `DsDynamicScrollableDropdownComponent` do not load the previously selected value when the component/page is reloaded.

**To Reproduce**
Steps to reproduce the behavior in current demo:
1. Start a new submission
2. Fill in some fields and select a value for the dc.type dropdown field
3. Save the submission
4. Reload the page
5. Other fields are filled, but the dropdown shows an empty value (the value is saved in the item but the component has not loaded the value)

**Expected behavior**
The field should shown the previously selected and saved value after reload

**Related work**
I think this bug has been introduced in this PR #2733 , the component should call to `setCurrentValue(this.model.value, true);` during the initialization but this call has been removed.

Probably adding this call during component initialization can fix the problem:

```
if (this.model.value) {
   this.setCurrentValue(this.model.value, true);
}
```

### PR DESCRIPTION
**Pull request by jensvannerum**
## References
* Fixes #2500
* Fixes #2805 

## Description
These changes allow for keyboard navigation in submission dropdowns

## Instructions for Reviewers
This PR modifies the `DsDynamicScrollableDropdownComponent` to support keyboard navigation. This is done by calling the already existing `getVocabularyEntriesByValue` instead of just calling `getVocabularyEntries` like done before.
Some helper methods where needed to handle the user input as we don't want to allow all characters. A method for handling user input already existed (`selectOnKeyDown`) so this was pretty straight forward.

Also moved the code from the `ngOnInit` method away to a reusable `loadOptions` method.

**how to test this PR**
This can be tested against the demo instance (demo.dspace.org) using the "type" dropdown in submission.

However I would recommend to test this locally and add a lot of values to the dropdown starting with the same letter(s) so you can verify that the scrolling / pagination functionality also works when filtering results.

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by alanorth** [comment]
Thank you, @jensvannerum. This allows the list to be _filtered_ with the keyboard, but it is still not possible to _select_ the value without using the mouse to click it. Our editors are very used to doing this from the DSpace 6 XMLUI submission form and it's important for accessibility as well. Do you think it would be possible to implement?

Also, I noticed that the matching occurs on the stored values, but I'm wondering if we are hitting a similar issue to https://github.com/DSpace/dspace-angular/issues/2724. Here I have a vocabulary with SPDX licenses. The displayed values are human readable, but the stored values are like "CC-BY-4.0":

2024-01-11T11:50:59,022148059+03:00-fs8

I can type "CC-", but as soon as I type "CC-B" the filtered list goes blank. Similary, I can type "4." and the list filters, but when I type "4.0" the list goes blank.

<hr />

For reference, the configuration for this vocabulary is like:

```console
       <pair>
         <displayed-value>Creative Commons Attribution 4.0 (CC BY 4.0)</displayed-value>
         <stored-value>CC-BY-4.0</stored-value>
       </pair>
```

**Comment by jensvannerum** [comment]
Thanks for your feedback @alanorth, it indeed seems like the filter is being done on the value of the vocabulary, not the label, this is a separate issue in the back-end that I fixed and will make a PR linked to this one for.

As far as the keyboard selection goes, how do you visualise this ?

It is still possible to enter the list of filtered values by pressing Tab like before and navigating with the arrow keys and enter. I am assuming you would like to be able to instantly press enter but this would only be possible when only 1 value is remaining in the filtered list.

**Comment by alanorth** [comment]
> the filter is being done on the value of the vocabulary, not the label, this is a separate issue in the back-end that I fixed and will make a PR linked to this one for.

It's out of the scope of this PR I think, but good to know. For some vocabularies the display value and the stored value are the same, but not always. If it is possible to search both the display and the stored values that would be nice.

> As far as the keyboard selection goes, how do you visualise this?

I think it should work as close to a _normal_ HTML input as possible. Try for yourself in GitHub's search bar, google.com, or even a [simple HTML form input element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input). If you type a few characters and press the down arrow key you can select values without needing the mouse.

Thank you!

**Comment by jensvannerum** [comment]
@alanorth I've updated the PR with keyboard navigation that matches the native html functionality as closely as possible

**Comment by alanorth** [comment]
Thank you @jensvannerum. I'm having problems applying the last commit in this patch series:

[110088: changes to keyboard navigation / selection](https://github.com/DSpace/dspace-angular/pull/2733/commits/05eb21250efcbe94fbb174d35bf170663a0d8b13)

 I'm not exactly sure why or how, but the state of your `src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html` seems different than the one on `main`.

**Review by alanorth — APPROVED** [review]

**Comment by alanorth** [comment]
Thanks again @jensvannerum. I re-based your branch on top of latest `main` locally and tested it in combination with https://github.com/DSpace/DSpace/pull/9276 and the experience is working well—much more like a native HTML form element.

I'm not sure why I had issues with the branch. I have rebased (and squashed your four commits into one) on top of the latest `main` and merged manually: c02b46ca7d4c5baad8c8902bd7a6dc56c4ee8a0b. I will port it to `dspace-7_x` as well.

**Comment by tdonohue** [comment]
NOTE:  Despite this looking like it was simply "closed", **this PR was merged manually** via https://github.com/DSpace/dspace-angular/commit/c02b46ca7d4c5baad8c8902bd7a6dc56c4ee8a0b  (as noted in previous comment). 

This confused me at first, so I wanted to call it out as the PR status of "Closed" implies that it wasn't merged.

**Comment by alanorth** [comment]
@tdonohue Thanks. Yes I know about the other options for merging on GitHub. The problem is that you can _rebase_ or you can _squash_—but not both! It's very easy to do via the `git` command line. I considered doing the work manually and then force pushing to the branch, but the submitter did not check the box allowing maintainers to update their branch. And seeing as this was a `1 APPROVAL` I figured it wasn't too big of a deal.

Only down side is that we have a red "Closed" badge on GitHub...

**Comment by alanorth** [comment]
Oops, it seems this introduced a new bug where dropdown values are cleared when moving between submission steps. See:

[Screencast from 2024-01-30 11-38-39.webm](https://github.com/DSpace/dspace-angular/assets/191754/a884ec57-f62f-40fb-91e3-f6d436008e7b)

@jensvannerum would you be able to take a look at this? Hopefully something minor in the implementation. Thank you!

**Comment by jensvannerum** [comment]
Re-opened this request since this introduced a new bug which I fixed now in context of #2805

**Comment by tdonohue** [comment]
@alanorth or @toniprieto : Could one of you test this to verify it now fixes #2805 ?

(@jensvannerum : Just a sidenote... in the future we may want to open a separate PR instead of reopening the same PR.  This entire PR has gotten confusing as your prior fixes applied to `main` in https://github.com/DSpace/dspace-angular/commit/c02b46ca7d4c5baad8c8902bd7a6dc56c4ee8a0b are no longer visible in this PR.  Now the PR only shows your *brand new* fixes.  This makes it harder for others to understand the changes that were necessary to fix this issue.  For now though, we can go with this approach. Just wanted to point out that we should always try to create a new PR once a PR is closed/merged.)

File: src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts [hunk 1]
```diff
@@ -79,6 +79,10 @@ export class DsDynamicScrollableDropdownComponent extends DsDynamicVocabularyCom
       tap(() => this.loading = false)
     ).subscribe((list: PaginatedList<VocabularyEntry>) => {
       this.optionsList = list.page;
+        if (this.model.value) {
+          this.setCurrentValue(this.model.value, true);
+        }
```
Comment (toniprieto) [inline src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts:84]: This call is now inside the `loadOptions()` method which can be called multiple times. The original code only made this call during initialization, in the `ngOnInit()` method. I would add a change to make this call only during initialization, perhaps by adding a new boolean parameter to `loadOptions()` to indicate that it is the call made from `ngOnInit()`

File: src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts [hunk 2]
```diff
@@ -88,6 +92,11 @@ export class DsDynamicScrollableDropdownComponent extends DsDynamicVocabularyCom
       this.selectedIndex = 0;
       this.cdr.detectChanges();
     });
+
+    this.group.get(this.model.id).valueChanges.pipe(distinctUntilChanged())
+      .subscribe((value) => {
+        this.setCurrentValue(value);
+      });
```
Comment (toniprieto) [inline src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts:99]: I would move this part to the end of `ngOnInit()`, otherwise this subscription will be created many times.

**Review by toniprieto — COMMENTED** [review]
Thanks @jensvannerum , it's solve the issue, though I would make some additional changes to make it more similar to the original code. Comments below:

**Comment by alanorth** [comment]
Thanks @jensvannerum. I tested this patch by cherry-picking the two latest commits into my 7.6 branch, then starting a new item submission. The drop downs are filterable with the keyboard and selected values are kept as expected when moving between submission sections. I was able to deposit the item successfully and all metadata was preserved.

@tdonohue I'm not sure what we want to do about the commits here, can we merge a pull request twice on GitHub? It certainly seems so in the UI...

**Comment by tdonohue** [comment]
**NOTE: This PR was merged in several stages:**
* Part 1 of PR (first 5 commits)
    * Manually merged/squashed to `main` in https://github.com/DSpace/dspace-angular/commit/c02b46ca7d4c5baad8c8902bd7a6dc56c4ee8a0b
    * Manually merged/squashed to `dspace-7_x` in #2764
* Part 2 of PR (last 2 commits)
    * Merged to `main` via this PR
    * Manually merged to `dspace-7_x` via #2821
