### PR TITLE
Store the state of the computed filters

### LINKED ISSUE #4097: 7.6.3 / 8 - Search facet filters disappear on mydspace page under circumstances
## Describe the bug
On the mydspace page the search filters will fail to load when changing the scope from submissions to workflow tasks and back.

## To Reproduce
**Tested locally and on demo.dspace.org**
Backend and Frontend is 7.6.3.
The testsystem is Ubuntu 22.04.5 LTS / OpenJDK 11.0.26 / Node 18.18.0 / PG 14 / Solr 8.11.4 and 9.7.
In my case the bug appears with and without apache as proxy.

It can be reproduced on demo.dspace.org see the screenshots taken from.

Open the mydspace page

Image

Change the "Show" dropdown from "Your submissions" to " Workflow tasks"

Image

Change again the dropdown back to "Your submissions"

Image

The filters are not beeing reloaded again.

## Expected behavior
The search filters should always be visible.

## Related work
https://github.com/DSpace/dspace-angular/issues/4053
https://github.com/DSpace/dspace-angular/pull/4077

### PR DESCRIPTION
**Pull request by sergius02**
## References
* Fixes #4097 

## Description
Store the state of the computed filters in the array finalFiltersComputed.

## Instructions for Reviewers
The counter filtersWithComputedVisibility doesn't store the count of filters computed when you change between options in the select box in /mydspace, causing the ngIf in the HTML is always false, and no filters options render on the web.

List of changes in this PR:
* First, countFiltersWithComputedVisibility now store the count every time a new filter is "computed" till it reach the maximum filters configured.
* Second, added some utility functions to find the current and final counter, and a function to update the count.
* Third, update the ngIf, to use the new functions.
* Fourth, removed the trackBy: trackUpdate in the ngFor because when you enter in /mydspace from the link in the dropdown it seems that it interferes.

How to test:
1. Enter in /mydspace from URL or from the link in the dropdown when you are logged in.
2. Change between options in the select box from the sidebar
3. The filters should be loaded without problem

## Checklist

- [ ] My PR is **created against the `main` branch** of code (unless it is a backport or is fixing an issue specific to an older branch).
- [x] My PR is **small in size** (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR **passes [ESLint](https://eslint.org/)** validation using `npm run lint`
- [x] My PR **doesn't introduce circular dependencies** (verified via `npm run check-circ-deps`)
- [x] My PR **includes [TypeDoc](https://typedoc.org/) comments** for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR **passes all specs/tests and includes new/updated specs or tests** based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] My PR **aligns with [Accessibility guidelines](https://wiki.lyrasis.org/display/DSDOC8x/Accessibility)** if it makes changes to the user interface.
- [ ] My PR **uses i18n (internationalization) keys** instead of hardcoded English text, to allow for translations.
- [x] My PR **includes details on how to test it**. I've provided clear instructions to reviewers on how to successfully test this fix or feature.
- [ ] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [ ] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by kshepherd** [comment]
@alanorth does this address the problem you've seen in 7.6.3?

**Comment by alanorth** [comment]
@kshepherd I will try to test it this week. I still haven't managed to reproduce the bug reliably, but I see it when browsing.

**Comment by alanorth** [comment]
I found a way to reproduce a related issue in Discovery search (see [comment in #4097](https://github.com/DSpace/dspace-angular/issues/4097#issuecomment-2775127830)) and this PR fixes it.

+1 from me on functionality.

**Comment by ovali** [comment]
This PR fixes the bug with the filters on the mydspace page for my 7.6.3 based branch. Thumbs up and thank you for providing this.

**Comment by ovali** [comment]
Anyone willing to review and approve this ?

**Comment by tdonohue** [comment]
@sergius02 :  Could we get a version of this PR created for the `main` branch?  That'd help me in my testing.

It appears (from discussion in this PR and on the ticket) that this bug is found to impact 7.x, 8.x and `main`.  It sounds like a few people have found this to work for 7.x.   Before we merge it though, I'd like to see a separate PR created for `main`, as that'd allow me to more easily verify the behavior there  (I cannot get this PR to work with `main` as it has major merge conflicts there).

In the meantime, anyone else is welcome to provide your reviews/approval on this PR.  Reminder that we accept reviews from *anyone*, and community reviews can help us get PRs merged more rapidly.

**Comment by alanorth** [comment]
For what it's worth, I'm running this in production on DSpace 7.6.3. I didn't notice the bug on the MyDSpace page, but this fixes [a bug that I showed with filters on the normal Discovery search page](https://github.com/DSpace/dspace-angular/issues/4097#issuecomment-2775127830).

**Comment by sergius02** [comment]
> @sergius02 :  Could we get a version of this PR created for the `main` branch?  That'd help me in my testing.

Ok, I'll try to do a port for the main branch

**Comment by sergius02** [comment]
I've made a PR for the main branch here https://github.com/DSpace/dspace-angular/pull/4160

File: src/app/shared/search/search-filters/search-filters.component.ts [hunk 1]
```diff
@@ -127,7 +133,122 @@ export class SearchFiltersComponent implements OnInit, OnDestroy {
...
+        }),
+        // Check if we've reached the total after incrementing
+        map(result => {
+          if (result.currentComputed === result.totalFilters) {
+            // If we've reached the total, update final filters count
+            this.updateFinalFiltersComputed(this.currentConfiguration, result.currentComputed);
+          }
+          return result;
+        })
+      ).subscribe().unsubscribe(); // Execute the pipeline and immediately unsubscribe
```
Comment (FrancescoMolinaro) [inline src/app/shared/search/search-filters/search-filters.component.ts:191]: Hi @sergius02 , can you please change this and instead us take(1) at the end of the pipe?
You're subscribing and unsubscribing right away, which is a kind of anti pattern in angular.

**Review by FrancescoMolinaro — CHANGES_REQUESTED** [review]
Hi @sergius02 , thanks for these changes, the PR looks good to me, I have just a small change request, if you could please have a look that would be great.

Thanks!

File: src/app/shared/search/search-filters/search-filters.component.ts (hunk 1 above)
Comment (sergius02) [reply src/app/shared/search/search-filters/search-filters.component.ts]: Done!

**Comment by saschaszott** [comment]
@sergius02 , thanks for your contribution. This PR fixes the UI freeze, but it does not solve the following problem: after switching the Discovery Configuration in the dropdown, the frontend still requesting filters (facets) from the backend that are no longer valid for the newly selected Discovery Configuration? This is ultimately the reason for the 400 Bad Request errors returned by the backend (can be found in the JS console or in the DSpace backend log file `dspace.log`). Do you have any idea how to solve this problem?

File: src/app/shared/search/search-filters/search-filters.component.ts [hunk 2]
```diff
@@ -90,7 +97,6 @@ export class SearchFiltersComponent implements OnInit, OnDestroy {
   ngOnInit(): void {
     this.router.events.subscribe(() => {
```
Comment (FrancescoMolinaro) [inline src/app/shared/search/search-filters/search-filters.component.ts:98]: Hi @sergius02 , sorry if I come back with another change request, I didn't see it at first as it is not part of your code changes, anyway I think we might need to add this subscription to the subs array, so that we avoid performance issue leaving a subscriber always active.

**Review by FrancescoMolinaro — CHANGES_REQUESTED** [review]
Hi @sergius02 , thanks again for your changes, I gave a second look to the PR and found a small issue on the component, is not related to your code changes but I think is better if we address it in this PR, could you please have a look?

Thanks in advance!

File: src/app/shared/search/search-filters/search-filters.component.ts (hunk 2 above)
Comment (sergius02) [reply src/app/shared/search/search-filters/search-filters.component.ts:98]: Hi @FrancescoMolinaro, this subscription was made by @anaparvo to fix a similar issue with the search filters https://github.com/DSpace/dspace-angular/pull/4077. But I think my PR solves that too. I'm testing in my local machine without this subscription and it works.

Comment (sergius02) [reply src/app/shared/search/search-filters/search-filters.component.ts]: Ok, I've removed that subscription

**Comment by tdonohue** [comment]
@sergius02 : This was unable to be automatically ported to 8.x (see dspace-bot message above).  Could you please create a PR against `dspace-8_x` in order to apply these changes to that release?

**Comment by sergius02** [comment]
@tdonohue I've created a new PR with the port at https://github.com/DSpace/dspace-angular/pull/4179
