### PR TITLE
fix for bitstreams are not visible to crawlers when caching is enabled

### LINKED ISSUE #2333: Bitstreams are not visible to crawlers when caching is enabled
**Describe the bug**
When the bot cache SSR is enabled the bitstreams are visible to crawlers only if the page is not cached.
This is due to the redirect, to bitstream content, that happens only the first time the bitstream download page is served, the following times the download page is returned with 200 and no redirect is done 

**To Reproduce**
1. run application with SSR enabled
2. take a download page url of an existing bitstream, e.g.: http://localhost:4000/bitstreams/UUID/download
3. by a terminal run wget http://localhost:4000/bitstreams/UUID/download
4. first time the bitstream shuold be downloaded properly
5. running the command again should lead only to download the html page and not the bitstream

**Expected behavior**
the bistream shuold be accessible for crawlers even if the cache is enabled

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes #2333

## Description
With this PR only successful page are saved into the SSR cache. In this way bitstream download page which return a 302 code is not saved 

## Instructions for Reviewers
check issue described into #2333 is fixed

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: server.ts [hunk 1]
```diff
@@ -479,6 +481,15 @@ function saveToCache(req, page: any) {
   }
 }
 
+/**
+ * Check if status code is different from 2XX
+ * @param statusCode
+ */
+function hasNotSucceeded(statusCode) {
+  const rgx = new RegExp(/20+/);
```
Comment (tdonohue) [inline server.ts:489]: Shouldn't we make sure this *starts* with `20`?

In other words, I wonder if this should be more strict.. like `/^20+/`.  Otherwise it's possible that "420" would match.  It's an "unofficial" code but it used to exists in Spring, see https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Unofficial_codes

**Review by tdonohue — APPROVED** [review]
@atarix83 : I tested and reviewed this today.  Looks good with a minor suggestion above (which might be good to fix up prior to merging)

I was able to verify the bug using the demo site (demo7.dspace.org) where it's reproducible when using `wget` to download a bitstream (per instructions in #2333).  First download works and the second one downloads the homepage's HTML.

I also verified this PR fixes the bug (bitstream download page is never cached and always results in a "CACHE MISS" if you turn on "debug: true" in caching options).

I also tested caching in general and verified that the anonymousCache and botCache appear to still work fine.  No noticeable issues with no longer caching non-2xx responses.

File: server.ts (hunk 1 above)
Comment (tdonohue) [reply server.ts:489]: I verified locally that this code still works if you change this line to 
```
const rgx = new RegExp(/^20+/);
```

While I think your code is *likely* OK, I'd recommend we make this Regex more strict to avoid any unexpected issues later on.

Comment (atarix83) [reply server.ts]: done
