### PR TITLE
Admin search dialogs

### LINKED ISSUE #831: Freshly created collection does not get pre-selected for Item insertion
1. Create top-level Community "Community 1"
2. It gets displayed in view mode
3. Pick option to create new Collection
4. Community "Community 1" is preselected in "new Collection" Community selector : "search.resourceid:047eb94a-d0d0-41bd-b761-6643d6d253ef"
5. Pick "Community 1" and add "Collection 1"
6. Collection "Collection 1" is displayed in view mode
7. Pick option to add new Item
8. New Item dialog does not preselect the "Collection 1" in collection picker

Expected - the collection, which is currently open in DSpace  (view or edit modes) should be pre-selected in collection picker.

### LINKED ISSUE #843: Default selection in create/edit screen is unclear
**Describe the bug**
Test users have reported difficulty in understanding the behavior of the administrative edit / create features (community, collection, item). The uuid of the current object that is when possible offered as a default choice for the feature is not intuitive for a normal user, the title of the object would be much better.

**To Reproduce**
1. login as an admin / user with sufficient edit permission
2. go to one community
3. use the create community/collection or the edit community/collection left menu 

**Expected behavior**
The user should see the title of the community where the create action will occur or the title of the object that he is going to edit. The uuid must be keep as an hidden parameter used by the application. The uuid can be eventually keep visible together with the title and the search should retain the possibility to work directly with an uuid

### LINKED ISSUE #889: The "new" admin sidebar menu options don't provide enough context
**Describe the bug**
We find users are confused by the new → collection and new → item admin sidebar options.
If you select new → collection for example, you see a dialog that says: "Search for a community", with a list of communities below. For inexperienced users it isn't clear _why_ they need to search for a community. The new → item dialog has the same issue.

Simply adding a bit of text above the search box that says something along the lines of: "Search for a community to create the collection in" would go a long way.

**To Reproduce**
1. Authenticate as an admin
2. in the sidebar, select new → collection or new → item
3. Look at the dialog that appears.

**Expected behavior**
The user should be told why they need to seach for a community or collection when creating a collection or item.

**Related work**
It would make sense to solve this in the context of #843, #831 and #890

### LINKED ISSUE #890: The new/edit admin menu dialogs are inconsistent
**Describe the bug**
The dialogs you get to search for a DSO when you use the new or edit admin sidebar features are inconsistent.

The new → item search dialog improves upon the others by adding the parent object to each result (that way, if you have multiple collections with the same name, you can tell them apart using their parent communities), and by adding the ability to scroll down to get the next page of results.

However these improvements were never added to any of the other dialogs, making the user experience inconsistent.

**To Reproduce**
1. Authenticate as an administrator
2. In the sidebar, select new → item
3. Compare this to edit → collection for example: it is the same search, but it looks different and is a lot less user friendly

**Expected behavior**
I expect all these dialogs to work in a consistent manner, and to have the features (parent reference, scroll for the next page) that the new → item dialog has.

**Related work**
- The PR that added the new → item dropdown: #708
- It would make sense to solve this in the context of #843, #831 and #889

### PR DESCRIPTION
**Pull request by Atmire-Kristof**
## References
This PR:
- fixes #831
- fixes #843 
- fixes #889
- fixes #890

## Description
This PR improves the modals to search for objects using the sidebar functions like create/edit item/collection/community etc.
It also adds a button to every item/collection/community page linking to the object's edit page for easy accessibility (only when the user is logged in and has edit permissions)

## Instructions for Reviewers

When opening a modal to edit/create an object:
- If the modal is accessed from a DSpaceObject's page (e.g. an item page), that object will by default show up on top of the search results (until the user starts typing a search query). I'll be referring to this object as the "current object" throughout this PR.
- The listed objects now contain a custom template defined by annotation @listableObjectComponent with context SideBarSearchModal (for any listed item that is not the current object) and SideBarSearchModalCurrent (for the listed item that is the current object)
- All of the current objects will use the template `sidebar-search-list-element.component.html`, which displays 3 lines of text for each object:
-- The title of the object's parent
-- The title of the object itself
-- A description of the object
-- All of the above are customisable by overwriting the parent component (`SidebarSearchListElementComponent`)'s getters: `getParentTitle()`, `getTitle()` and `getDescription()`
- The current object is highlighted by default (a custom template can be created using context SideBarSearchModalCurrent)
- The list is infinitely scrollable. It will load new results when scrolling down with a page size of 10 until there are no more.
- For new item and collection, a header has been added explaining what the user is searching for

Upon visiting an item/collection/community's page:
- When anonymous, it should look exactly the same as before
- When logged in as a user that has edit items for said object, it should display a button on the top right of the page, linking to the object's edit page for easy access

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

This PR has more than 1,000 lines of code mostly because I had to create a new template for each DSO and entity type. All of these templates are very similar.

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs for any bug fixes, improvements or new features. A few reminders about what constitutes good tests:
    * Include tests for different user types (if behavior differs), including: (1) Anonymous user, (2) Logged in user (non-admin), and (3) Administrator.
    * Include tests for error scenarios, e.g. when errors/warnings should appear (or buttons should be disabled).
    * For bug fixes, include a test that reproduces the bug and proves it is fixed. For clarity, it may be useful to provide the test in a separate commit from the bug fix.
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/master/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

File: src/app/shared/object-list/sidebar-search-list-element/item-types/publication/publication-sidebar-search-list-element.component.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+@listableObjectComponent(ItemSearchResult, ViewMode.ListElement, Context.SideBarSearchModalCurrent)
+@Component({
+  selector: 'ds-publication-sidebar-search-list-element',
+  templateUrl: '../../sidebar-search-list-element.component.html'
+})
+/**
+ * Component displaying a list element for a {@link ItemSearchResult} of type "Publication" within the context of
+ * a sidebar search modal
+ */
+export class PublicationSidebarSearchListElementComponent extends SidebarSearchListElementComponent<ItemSearchResult, Item> {
```
Comment (tdonohue) [inline src/app/shared/object-list/sidebar-search-list-element/item-types/publication/publication-sidebar-search-list-element.component.ts:21]: I'm surprised to see this named `Publication` (which is an type of Entity) instead of just being a generic `ItemSidebarSearchListElement`.  Logically, many more people are going to use generic Items than Publication Entities.  So, even if this same file can be used for *both* types, we probably should think about naming it `ItemSidebarSearchListElement`.

That said, as I noticed this, I looked around in other areas of the code, and we seem to have developed an "antipattern" of having components starting with `Publication*` even if they also are used for generic Items....another example is the `PublicationComponent` itself: https://github.com/DSpace/dspace-angular/blob/main/src/app/%2Bitem-page/simple/item-types/publication/publication.component.ts  (which seems to have a side effect of displaying "Publication:" before every Item title.

So, we don't necessarily need to fix this in this PR.  However, I'd argue we need to change the names of these components to start with `Item` or `GenericItem`.  I can open this as a separate ticket though, as I suspect this is better done separately.

**Review by tdonohue — APPROVED** [review]
👍 @Atmire-Kristof: Overall this looks great.  There's a lot of code here, but much of it is creating the same `SidebarSearchListElementComponent` for each object type.

I tested the scenarios in all the bugs referenced by this PR, and they all look to be fixed to me.  I also like the new Edit button.

My only comment (see below) is a separate issue that I noticed while reviewing this PR.  So, I'll create a separate ticket to track it.  Thanks!

File: src/app/shared/object-list/sidebar-search-list-element/item-types/publication/publication-sidebar-search-list-element.component.ts (hunk 1 above)
Comment (tdonohue) [reply src/app/shared/object-list/sidebar-search-list-element/item-types/publication/publication-sidebar-search-list-element.component.ts:21]: I've logged the above comment in #936

**Review by atarix83 — APPROVED** [review]
thanks @Atmire-Kristof for this PR

Code looks good to me, I've tested and all seems to work fine
