### PR TITLE
680 Fix change event reference for recent submission

### LINKED ISSUE #680: Recent Submissions pagination is not reloading properly
When browsing a collection with more than one page, advancing to another (next or previous) page does not work.  The page indicator moves as expected, but the items on the page do not change.  In addition, mousing over the items results in a 'flicker' as if some sort of mouseover event is being handled.  A page refresh results in proper display.  Tested on chrome, safari, edge, and firefox with the same results.

UPDATED DESCRIPTION (Based on comments below):
The problem seems to be in the "Recent Submissions" listing of a Collection.  Pagination is not working properly as the second page is never loaded when clicking on next page.

How to reproduce:
* Find a Collection with more than one page of "Recent Submissions". For example, this collection on the demo site: https://dspace7-demo.atmire.com/collections/8ad84c46-bdf1-4558-9b90-5c43ff396980
* Click on page 2 (or next page).  You will remain on the first page of items even though the screen looks to reload.
* If you click the reload button in your browser, you when then jump to the second page of items.

### PR DESCRIPTION
**Pull request by AndrewZWood**
Fixes #680 
I've updated the event change references to valid ones so the `onPaginationChange(event)` functions properly. Tested my additions in my local environment.

NOTE: The following error was reported before my changes but seems rather strange that this particular error is still present in my console given I've seen the pattern I used elsewhere in the code base without such an error. It's unclear to me why `paginationConfig` properties throw an error when attempting to be set. Would be great to get some insight on this: 
`core.js:4002 ERROR TypeError: Cannot read property 'currentPage' of undefined
    at CollectionPageComponent.push../src/app/+collection-page/collection-page.component.ts.CollectionPageComponent.onPaginationChange (collection-page.component.ts:112)
    at SafeSubscriber._next (collection-page.component.ts:102)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:194)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:132)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:76)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
    at TakeSubscriber.push../node_modules/rxjs/_esm5/internal/operators/take.js.TakeSubscriber._next (take.js:40)
    at TakeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
    at BehaviorSubject.push../node_modules/rxjs/_esm5/internal/BehaviorSubject.js.BehaviorSubject._subscribe (BehaviorSubject.js:22)
    at BehaviorSubject.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe (Observable.js:43)`

### CODE REVIEW

**Review by tdonohue — COMMENTED** [review]
@AndrewZWood : I've looked at this and the code seems to work.  I *do* still see the TypeError you mentioned.  It seems to *ONLY* occur on the initial page load (for a Collection page) and not after clicking to the next page or similar.  Here's the error I see:
```
ERROR TypeError: Cannot read property 'currentPage' of undefined
    at n.onPaginationChange (collection-page.component.ts:112)
    at t._next (collection-page.component.ts:102)
    at t.__tryOrUnsub (Subscriber.js.pre-build-optimizer.js:194)
    at t.next (Subscriber.js.pre-build-optimizer.js:132)
    at t._next (Subscriber.js.pre-build-optimizer.js:76)
    at t.next (Subscriber.js.pre-build-optimizer.js:53)
    at t._next (take.js.pre-build-optimizer.js:40)
    at t.next (Subscriber.js.pre-build-optimizer.js:53)
    at t._subscribe (BehaviorSubject.js.pre-build-optimizer.js:22)
    at t.e._trySubscribe (Observable.js.pre-build-optimizer.js:43)
```

If you look closely at that message, it looks to be calling out line 102 in the `ngOnInit()` function here: https://github.com/DSpace/dspace-angular/blob/6c3c1ad433b6ba3b1e1c248ce4d3fa9df4bf7908/src/app/%2Bcollection-page/collection-page.component.ts#L102

So, while your new code seems correct, I think the `ngOnInit()` needs updates.  The `ngOnInit()` code in that area seems odd to me...I'm not very familiar with this code, but in other components using similar pagination (e.g. [top-level-community-list.component.ts](https://github.com/DSpace/dspace-angular/blob/main/src/app/+home-page/top-level-community-list/top-level-community-list.component.ts)) I'm not seeing that same ngOnInit() code.

This might be something @artlowel could answer more quickly than I could...but I'm wondering myself if that `ngOnInit()` code is needed or simply needs larger refactoring.

**Comment by artlowel** [comment]
The issue here is [this line](https://github.com/atmire/dspace-angular/blob/6c3c1ad433b6ba3b1e1c248ce4d3fa9df4bf7908/src/app/+collection-page/collection-page.component.ts#L102). It passes the route params as an `onPaginationChange` event, but that's no longer valid. The structure of those events has changed. That change is the reason for this PR: it fixes the logic inside onPaginationChange. 

If you create an interface for `onPaginationChange` events (they have a [`pagination: PaginationComponentOptions` and a `sort: SortOptions` property](https://github.com/atmire/dspace-angular/blob/6c3c1ad433b6ba3b1e1c248ce4d3fa9df4bf7908/src/app/shared/pagination/pagination.component.ts#L357-L369)), and add that as a type to the `event` param for `onPaginationChange` the compiler will point out these kinds of errors.

For now, that call using the route params can just be removed. The pagination component itself will parse the route for now. The ticket Tim mentioned above will ensure it moves to a more suitable location later.

**Comment by AndrewZWood** [comment]
@tdonohue Updated code to reflect on @artlowel 's input. Error is no longer presents and I have tested functionality in my local environment.

**Comment by tdonohue** [comment]
@AndrewZWood : It looks like you need to rebase on the latest `main` code as there are merge conflicts now.  Keep in mind that we recently merged an update to Angular 10, which also changed some of the `lint` settings...so you may need to make minor formatting changes too after rebasing (if `yarn lint` throws errors).

**Comment by AndrewZWood** [comment]
@tdonohue Sorry about that....rebase and checked against the newer lint settings.

File: src/app/shared/pagination/paginationChangeEvent.interface.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import {PaginationComponentOptions} from './pagination-component-options.model';
+import {SortOptions} from '../../core/cache/models/sort-options.model';
+
+export interface PaginationChangeEvent {
```
Comment (tdonohue) [inline src/app/shared/pagination/paginationChangeEvent.interface.ts:4]: Tiny thing, please add TypeDocs to describe this new interface.  We require TypeDocs/comments for any public classes/interfaces/methods.

**Review by tdonohue — APPROVED** [review]
👍 @AndrewZWood , I tested this today & it fixes the bug!  The code also looks good to me, although we **do** need TypeDocs/comments to describe the new interface you are creating.  Once those comments are added, this is ready to merge.  Thanks!

**Comment by tdonohue** [comment]
Thanks @AndrewZWood ! Looks good now.  Merging
