### PR TITLE
Fix Author search result without co-author

### LINKED ISSUE #2203: Author search result without co-author being displayed when there are multiple authors in dc.contributor.author field
**Describe the bug**
If there are multiple authors in dc.contributor.author field, the search result only shows the author who is being searched. However, if the authors in dc.creator field, the search result shows all co-authors as well.

**To Reproduce**
1. Query "first" in search box - https://demo7.dspace.org/search?query=first
2. The result for https://demo7.dspace.org/items/1984e894-70ee-41ea-8566-83d6477139c2 only shows first as the author, the second author is not shown.

**Expected behavior**
Expect the co-authors in the search result as well.

**Related work**

### PR DESCRIPTION
**Pull request by oscar-escire**
Hi @tdonohue, I'm @jtimal partner, I like to share this PR with you:

## References
* Fixes #2203 

## Description
Add a method to search-result-list-element component to show all the authors and if the author's name is highlighted its displayed anyways (if author's list length allow it)

## Instructions for Reviewers
To reproduce the error we need an item with two or more dc.contributor.author:

- Create and deposit a new item
- Add to metadata two or more dc.contributor.author
- Use search tool to find the item

List of changes in this PR:
* Added a method to combine the highlighted authors and other authors' name
* Changed the method used to displayed the list of authors in result list

## Checklist
- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by oscar-escire** [comment]
Hi @tdonohue I added a commit removing some trailing spaces and removing some console.logs that I forgot

File: src/app/shared/object-list/search-result-list-element/search-result-list-element.component.ts [hunk 1]
```diff
@@ -47,6 +47,25 @@ export class SearchResultListElementComponent<T extends SearchResult<K>, K exten
     return Metadata.allValues([this.object.hitHighlights, this.dso.metadata], keyOrKeys);
   }
 
+  /**
+   * Gets all matching metadata string values from hitHighlights or dso metadata.
+   *
+   * @param {string|string[]} keyOrKeys The metadata key(s) in scope. Wildcards are supported; see [[Metadata]].
+   * @returns {string[]} the matching string values or an empty array.
+   */
+  allMetadataNoExcludingValues(keyOrKeys: string | string[]): string[] {
```
Comment (tdonohue) [inline src/app/shared/object-list/search-result-list-element/search-result-list-element.component.ts:56]: It'd be better to move this code into the `allMetadataValues()` method that already exists.  Currently, in this PR, you've removed all usages of `allMetadataValues()`, so that code is no longer used.   So, the simple solution here is to replace the code in `allMetadataValues()` with your new code.

**Review by tdonohue — CHANGES_REQUESTED** [review]
@oscar-escire : Thanks for this fix.  First, I can verify that your fix works.  However, I'd recommend removing your `allMetadataNoExcludingValues()` method and simply updating the existing `allMetadataValues()` method with your fixes.   Currently, the code in this PR is "messy" because it has two methods when it just needs one.

File: src/app/shared/object-list/search-result-list-element/search-result-list-element.component.ts (hunk 1 above)
Comment (oscar-escire) [reply src/app/shared/object-list/search-result-list-element/search-result-list-element.component.ts]: Hi @tdonohue Thanks, I agree with you, but at the start I didn't check if this method was used in others parts. I updated the PR with your recommendation.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @oscar-escire ! This now looks good to me.  I re-tested it today and it works well.
