### PR TITLE
Communities and collections not shown right after creation

### LINKED ISSUE #842: DSpace 7 - Subcommunities / Collections not shown immediately after creation
**Describe the bug**

Right after creating a subcommunity, if we go to the "parent-community" using the menu on the top of the screen, the new subcommunity just created, isn't shown, unless you refresh the browser.

**To Reproduce**

Create a subcommunity within a community.
Click on "All of DSpace" on the top of the page.
Select the "parent-community" within which you added the subcommunity.
The just created subcommunity doesn't appear in the list of the subcommunities.

**Expected behavior**

The expected behaviour was to see the just created subcommunty in the list of the subcommunities without the need of refreshing the browser.

### PR DESCRIPTION
**Pull request by corrad82-4s**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #842 

## Description

After a collection or community is created or deleted, href request to its parent is removed from requests cache, so that list of communities or collections belonging to a given community, at any level, from top level on, has to be reloaded and new collection / community is immediately displayed in case of creation or not displayed anymore in case of deletion.

## Instructions for Reviewers

a new function named `refreshCache` has been added to `CreateComColPageComponent` and `DeleteComColPageComponent`, and it is called by the `onSubmit` function of `CreateComColPageComponent` during the flow that observes result of `DSpaceObject` creation performed by `dsoDataService`, and by the `onConfirm` function of `DeleteComColPageComponent` during the flow that observes the result of `DSpaceObject` deletion performed by `dsoDataService`.

List of changes in this PR:
* `refreshCache` function in `CreateComColPageComponent` and its invocation
* `refreshCache` function in `DeleteComColPageComponent` and its invocation

To reproduce the bug: 

* Create a subcommunity within a community.
* Click on "All of DSpace" on the top of the page.
* Select the "parent-community" within which you added the subcommunity.
* The just created subcommunity doesn't appear in the list of the subcommunities.
* Delete a subcommunity within a community.
* Click on "All of DSpace" on the top of the page.
* Select the "parent-community" within which you deleted the subcommunity. 
* The just deleted subcommunity still appears in the list of subcommunities
* Create a collection within a community.
* Click on "All of DSpace" on the top of the page.
* Select the "parent-community" within which you added the collection.
* The just created collection doesn't appear in the list of the community collections.
* Delete a collection within a community.
* Click on "All of DSpace" on the top of the page.
* Select the "parent-community" within which you deleted the collection. 
* The just deleted collection still appears in the list of collections

To test changes: 

* Create a new top level community
* Newly created top level community should appear in dspace home page and in community-list page list
* Delete created top level community
* Deleted community should not appear anymore in DSpace home page and in community-list page list
* Create a new subcommunity
* Newly created subcommunity should appear immediately as child of its parent community in community-list page and between 'Communities of this community' section in community page
* Delete newly created subcommunity
* Deleted sub-community should not appear anymore  as child of its parent community in community-list page and between 'Communities of this community' section in community page
* Create a new collection of a Community
* Newly created collection should immediately appear between 'Collections of this community' section in community page
* Delete newly created collection
* Deleted collection should not appear anymore between 'Collections of this community' section in community page.

## Checklist

- [X] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [X] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [X] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [X] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

File: src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts [hunk 1]
```diff
@@ -65,4 +74,23 @@ export class DeleteComColPageComponent<TDomain extends DSpaceObject> implements
   onCancel(dso: TDomain) {
     this.router.navigate([this.frontendURL + '/' + dso.uuid + '/edit']);
   }
+
+  private refreshCache(dso: TDomain) {
```
Comment (tdonohue) [inline src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts:78]: These two methods seem identical to the ones in `create-comcol-page.component.ts`.   Just wondering if we should find a way to place these methods in one place so both components can use the same method?  It'd be easier to maintain if there was no duplication here.

**Review by tdonohue — COMMENTED** [review]
@corrad82-4s : I gave this a code review & test today.  First off, my tests show this works as described.  I'm no longer able to reproduce the caching issue that I saw previously.

The code also looks good overall. *However,* I have a few minor comments/questions inline below.  I'd also appreciate it though if  @artlowel can take a closer look at my feedback here & see if he agrees.

File: src/app/core/data/remote-data.ts [hunk 2]
```diff
@@ -55,4 +55,8 @@ export class RemoteData<T> {
     return this.state === RemoteDataState.Success;
   }
 
+  get hasNoContent(): boolean {
+    return this.statusCode === 204;
```
[the remark this answers is not in the document]
Comment (artlowel) [reply src/app/core/data/remote-data.ts:59]: I wouldn't touch the way that works now. The way the remotedata state is determined will change with the PR for #739, and that code takes 204 in to account: there is a NoContent interface and in the case of a 204 a RemoteData<NoContent> with the state successful will be returned. That way a service method can put in its signature that it expects a 204 response.

[the remark this answers is not in the document]
Comment (tdonohue) [reply src/app/core/data/remote-data.ts:59]: Since @artlowel notes this 204 response behavior will be cleaned up in a follow-up PR, I'm OK with the current approach as-is.  So, I'll mark this comment as "resolved".

File: src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts (hunk 1 above)
Comment (artlowel) [reply src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts:78]: I agree. It looks like refreshCache and parentCommunityUrl can be moved to ComColDataService. Both components already have a reference to it in `this.dsoDataService`.

File: src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts [hunk 3]
```diff
@@ -65,4 +74,23 @@ export class DeleteComColPageComponent<TDomain extends DSpaceObject> implements
...
+    const parentCommunityUrl = this.parentCommunityUrl(dso as any);
+    if (!hasValue(parentCommunityUrl)) {
+      return;
+    }
+    this.dsoDataService.findByHref(parentCommunityUrl).pipe(
+      getSucceededOrNoContentResponse(),
+      take(1),
+    ).subscribe((rd: RemoteData<TDomain>) => {
+      const href = rd.hasSucceeded && !isEmpty(rd.payload.id) ? rd.payload.id : 'communities/search/top';
```
Comment (artlowel) [inline src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts:87]: It would be better to not hard-code the path to the top endpoint. But rather use the HALEndpoinService to discover it using HAL links. 

If you replace `'communities/search/top'` with `this.halService.getEndpoint('communities/search/top')` it will still work if the rest api changes its url, because that way the parts of the path ('communities', 'search' and 'top') will be treated as subsequent HAL link names to follow from the root endpoint, rather than a URL.

File: src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts (hunk 1 above)
Comment (corrad82-4s) [reply src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts]: Thank you, I moved this function to ComColDataService and amended tests accordingly.

File: src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts (hunk 3 above)
Comment (corrad82-4s) [reply src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts]: Hard coded link has been replaced with HALEndpointService usage.

**Comment by tdonohue** [comment]
@corrad82-4s : Take a look at the review from LGTM above, it looks like in your refactor you've accidentally left *10* unused variables/classes around.  So, please see if you can clean up the issues reported by LGTM.  Thanks!

**Comment by corrad82-4s** [comment]
> @corrad82-4s : Take a look at the review from LGTM above, it looks like in your refactor you've accidentally left _10_ unused variables/classes around. So, please see if you can clean up the issues reported by LGTM. Thanks!

@tdonohue : sorry for this inconvenience. Updating it as soon as possible

**Review by artlowel — APPROVED** [review]
Thanks @corrad82-4s!

**Review by tdonohue — APPROVED** [review]
👍 Looks good. I gave this a test and it works as described.  Thanks @corrad82-4s!
