### PR TITLE
Fix issue with the admin sidebar scrollbar on Firefox/Windows

### LINKED ISSUE #2927: Testathon: Management sidebar cuts off first letter in Firefox
Firefox browser. When logging in as admin, the Management sidebar cuts off the first letter of the panel, whether or not the sidebar is pinned. When logging in as another persona, the Management sidebar displays properly, Screen recording is here: https://arizona.zoom.us/rec/share/DIXxStywY98TQbUmhJqoEWTVaL368rBVEy5PrSD8ijIJxkNTG_bC_KEhEgY3FLIx.me87iPI7Qbtvd8zJ?startTime=1712958202000

**To Reproduce**
1. Use Firefox
2. Login in the dspacedemo+admin@gmail.com persona.
3. Expand the sidebar, pin the sidebar.
4. The first letter of the first word is cut off, whether or not the sidebar is pinned.
5. This does not happen when logged in with other personas.
6. Maximizing the window didn't make a difference.

**Expected behavior**
I expected the sidebar to display fully without the first letter of the first word being cut off.

**Related work**
Link to any related tickets or PRs here.

### PR DESCRIPTION
**Pull request by davide-negretti**
## References
* Fixes #2927

## Description
This PR fixes the issues with the admin sidebar scrollbar on Firefox on Windows by allocating more space to the scrollbar.

## List of changes
* In the root component a class is added to identify the browser and the OS according to the user agent (e.g. `browser-firefox browser-firefox-windows`
* In the `admin-sidebar` component the value of `--ds-dark-scrollbar-width` is overridden when `browser-firefox-window` class is present

### Implementation notes
Note that `--ds-dark-scrollbar-width` has two purposes:
* define the scrollbar width (this is not supported by Firefox)
* allocate space to the scrollbar (`min-width: calc(var(--ds-admin-sidebar-collapsible-element-width) - var(--ds-dark-scrollbar-width));`)

## Additional notes
This PR allows to override any property of a CSS class as follows:

```css
.my-class {
  // class properties
  ::ng-deep {
    @at-root .browser-safari & {
      // override properties here
    }
  }
}
```

Currently only Safari and Firefox browsers and Windows OS are supported, but other browsers and OSs can be easily added.

## Further improvements

This PR solves the issue, but further improvements are required to make the scrollbar width smaller: see [this comment](https://github.com/DSpace/dspace-angular/issues/2927#issuecomment-2071941669)

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new libraries/dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR includes new features or configurations, I've provided basic technical documentation in the PR itself.
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

File: src/app/root/root.component.ts [hunk 1]
```diff
@@ -108,4 +142,23 @@ export class RootComponent implements OnInit {
       mainContent.focus();
     }
   }
+
+  getBrowserName(): string {
+    const userAgent = this._window.nativeWindow.navigator.userAgent;
```
Comment (tdonohue) [inline src/app/root/root.component.ts:147]: @davide-negretti : After merging this PR, I'm now noticing that I can get an error on this line when run via SSR:
```
ERROR TypeError: Cannot read properties of undefined (reading 'userAgent')
    at RootComponent2.getBrowserName (C:\\dspace-angular\dist\server\main.js:1:1008203)
    at RootComponent2.ngOnInit (C:\\dspace-angular\dist\server\main.js:1:1006659)
    at callHookInternal (C:\\dspace-angular\dist\server\main.js:1:4134206)
```


To reproduce:
1. Build in prod mode : `yarn build:prod; yarn serve:ssr`
2. Access the homepage & that SSR error will appear in the console window where you ran `yarn serve:ssr`.

Could you possibly provide a quick fix so that I don't have to revert this PR?
