### PR TITLE
No way to view an Item when in simple "Approve/Reject" workflow stage

### LINKED ISSUE #1236: No way to view an Item when in simple "Approve/Reject" workflow stage
**Describe the bug**
If you use the default 3-step approval workflow, the first stage is a simple "Approve/Reject" (with no option to Edit).  In that stage, the reviewer has no way to view the Item under review...this means they cannot see the files or metadata, so they have no context for accepting or rejecting.  Here's what a reviewer sees in that scenario (and the item is not clickable in any way)

acceptreject

**To Reproduce**
1. Enable the 3-step workflow on a Collection
2. Submit an Item to that Collection
3. Login as any user with review privileges in that first step. You'll see what is in the screenshot above.

**Expected behavior**
Perhaps we can add a simple "View" button similar to the one that appears in your list of submissions?  Since the reviewer *has permissions* to view the Item, if you determine the UUID of the Item in Workflow, you can actually see it's content by visiting `http://localhost:4000/items/[uuid]` in your browser.  Perhaps a simple link to that would suffice for 7.0, at least until a more advanced solution like #772 is implemented?

**Related work**
Related to #772

### PR DESCRIPTION
**Pull request by alemarte**
## References
* Fixes #1236

## Description
Reproducing the scenario described in the related ticket, we can now see a button to view details about the workflowitem.
Following this link land the user to a new page as visualized in screenshots below.

## Instructions for Reviewers

List of changes in this PR:
* An action button to view the workflow item has been added in case no edit action is present
viewaction1
* A new page component under the /workflowitems parent has been added to show the item related to the workflowitem. This route resolve the item following the relation workflowitem.item so, it should be visible only to those users with that specific permission.

viewaction2

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
Assigning this to @artlowel and I for review.  @artlowel , feel free to delegate as needed.  I'll also gladly do the initial review/test, if you need to concentrate more on a simple code review.

**Review by tdonohue — APPROVED** [review]
@alemarte : Gave this a test today & it looks good and works as described.  I just have one (hopefully minor) request.  

Would it be possible to add a `Back` button to the WorkflowItem View page (and/or provide a link back in the breadcrumbs)?  Currently, the only want to go back to your list of workflow items is to use the browser's back button. The browser's back button works fine, but on other pages we tend to have a `Back` button which provides a slightly better user experience.

If, for some reason, this proves to be too difficult to achieve, we can leave this PR as-is (which is why I'm submitting this as an approval).  But, I think a Back button would provide a better user experience here.

File: src/app/+workflowitems-edit-page/workflow-item-view/workflow-item-view.component.ts [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+   */
+  viewMode = ViewMode.StandalonePage;
+
+
+  constructor(protected route: ActivatedRoute) {
+  }
+
+  ngOnInit() {
+    this.wfi$ = this.route.data.pipe(map((data: Data) => data.wfi as RemoteData<WorkflowItem>), getRemoteDataPayload());
+    this.itemRD$ = this.wfi$.pipe(switchMap((wfi: WorkflowItem) => (wfi.item as Observable<RemoteData<Item>>).pipe(getAllSucceededRemoteData())));
```
Comment (artlowel) [inline src/app/+workflowitems-edit-page/workflow-item-view/workflow-item-view.component.ts:37]: I think you need `getAllCompletedRemoteData()` here. Because now it will simply keep loading if there's an error for any reason. And you [already have an alert in place](https://github.com/4Science/dspace-angular/blob/CST-4320/src/app/+workflowitems-edit-page/workflow-item-view/workflow-item-view.component.html#L7) to show errors

**Review by artlowel — CHANGES_REQUESTED** [review]
Thanks @alemarte!

It works, but currently it doesn't support entity pages. 

I also wonder why you went for a separate component here. If you were to re-use the regular item page component, but just add a new route to it, with a dedicated resolver to get the item from the WFI instead, it would give you all current (and future) features of the item page component without any additional effort

Tim's back button request would be a bit tricky though, but you could do that by setting e.g. `context: `[`Context.Workflow`](https://github.com/DSpace/dspace-angular/blob/fa36b3518d39095b61bf08d8e3e3421f64e38661/src/app/core/shared/context.model.ts#L9) in the route data, and only rendering that button in item-page component if the context is workflow

File: src/app/+workflowitems-edit-page/workflow-item-view/workflow-item-view.component.html [hunk 2]
```diff
@@ -0,0 +1,9 @@
+<div class="container" *ngVar="(itemRD$ | async) as itemRD">
+    <div class="item-page" *ngIf="itemRD?.hasSucceeded">
+        <div *ngIf="itemRD?.payload as item">
+            <ds-untyped-item [object]="item"></ds-untyped-item>
```
[the remark this answers is not in the document]
Comment (alemarte) [reply src/app/+workflowitems-edit-page/workflow-item-view/workflow-item-view.component.html]: Resolved by reusing the `ItemFullPageComponent`

File: src/app/+workflowitems-edit-page/workflow-item-view/workflow-item-view.component.ts (hunk 1 above)
Comment (alemarte) [reply src/app/+workflowitems-edit-page/workflow-item-view/workflow-item-view.component.ts]: Resolved by reusing the `ItemFullPageComponent`

**Comment by alemarte** [comment]
Thanks @artlowel for your feedback!

I've implemented the `ItemFromWorkFlowResolver` that inject the Item object into the `ItemFullPageComponent`.
Since the parent `WorkflowItemPageResolver` already inject the worfkflowitem, I've used this piece of information to discriminate the context. And so I could show the back button (and perform other minor customization such as hiding the simple view button) only when the page has been originated by a workflowitem.

**Review by artlowel — CHANGES_REQUESTED** [review]
Thanks for taking my feedback in to account @alemarte!

There are two minor issues remaining:

Currently you get the following error:

```
core.js:4442 ERROR TypeError: Cannot read property 'pipe' of undefined
    at ItemVersionsComponent.ngOnInit (item-versions.component.ts:115)
```

The reason is that the version link on the item wasn't resolved. The proper way of fixing this would be to add followLink('version') inside followLink('item') in your new resolver, but I tried that, and rest returns an error when you try to get the version of an item that's not yet archived.

So the best we can do for now is to put an `if (hasValue(this.item.version))` around [this block of code](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/item/item-versions/item-versions.component.ts#L113-L147) in the item versions component to ensure it no longer assumes the version property is there

Secondly @atarix83 has made the back buttons look and act the same everywhere in a recent PR (see e.g. the edit item page, status tab). Please use that same style, icon, and placement (aligned to the right) here as well.

File: src/app/+item-page/full/full-item-page.component.html [hunk 3]
```diff
@@ -29,6 +29,11 @@
       <ds-item-page-full-file-section [item]="item"></ds-item-page-full-file-section>
       <ds-item-page-collections [item]="item"></ds-item-page-collections>
       <ds-item-versions class="mt-2" [item]="item"></ds-item-versions>
+      <div class="button-row bottom" *ngIf="fromWfi">
+        <div class="text-right">
+          <a class="btn btn-outline-secondary mr-1" (click)="back()"><i class="fas fa-arrow-left"></i> {{'item.page.return' | translate}}</a>
```
Comment (artlowel) [inline src/app/+item-page/full/full-item-page.component.html:34]:
```suggestion
          <a class="btn btn-outline-secondary mr-1" href="javascript:void(0)" (click)="back()"><i class="fas fa-arrow-left"></i> {{'item.page.return' | translate}}</a>
```

An `<a>` tag needs an `href`, otherwise it isn't accessible by a screenreader. You can also tell because the hover color doesn't work if you omit the href.

**Review by artlowel — APPROVED** [review]
Thanks @alemarte 

I noticed one more small accessibility issue. 
Feel free to merge after it is fixed, no need for another review.
