### PR TITLE
browse-by-metadata-page works correctly on numeric 'value' param

### LINKED ISSUE #2128: browse-by-metadata-page does not work correctly on numeric "value" param
**Describe the bug**
We have metadata (Dewey Decimal Classification, DDC) wich is always saved on its numeric value like 000, 004, 220, etc.
When created an index for that field and configured in the Browse Configuration as

```webui.browse.index.5 = subjectddc:metadata:dc.subject.ddc:text```

this is available in the "All of Dspace" menu, selecting shows a result list of DDC subjects and their count.

When selecting a subject  in the results list , a new  list of items is shown - **despite the URL param ```value``` is numeric and starts with zero (0)**,
e.g. ```/browse/subjectddc?value=004``` the result is ```No items to show.``` and the text is ```Browsing by browse.metadata.subjectddc "4"```, e.g. the leading zeros are shortened.

This does not happen if value is 000 (see below) or any other value not starting with zero.
This is a problem of the SPA, the API works like expected, e.g. ```/server/api/discover/browses/subjectddc/items?spage=0&size=20&filterValue=004"``` returns the JSON with the item data.

**To Reproduce**
Any numeric value in an index with leading zeros will be shortened.

**Expected behavior**
Numeric URL values for browse index should be treated as string.

**Related work**
https://github.com/DSpace/dspace-angular/blob/1d58910d70f3d32d46d0cca2460f79f5d8b7dff1/src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts#L154
```params.value``` is the unmodified param from URL; this expression is responsible:
-  if ```params.value``` is emtpy, ```''``` is assigned
-  if ```params.value``` is assumed a number, leading zeros will be shortened by ```+params.value```
-  if ```params.value``` is a number with only zeros, ```+params.value``` will evaluate to boolean false and  ```params.value``` is assigned unmodified

Removing the first part ```+params.value``` solves the problem, but there might be a reason for that.

### PR DESCRIPTION
**Pull request by CrisGuzmanS**
Hello @tdonohue ✋. i already finished this issue. I will be attentive to any comments.
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #2128

## Description
Browse By Metadata page will work correctly on numeric 'value' param.

## Instructions for Reviewers
i just avoid the symbol "+" in "+startsWith" to prevent conversion from string to number.

1. login
2. select any section from "all of DSpace" that its index is according to a metadata value.
3. Search for an item that has leading "0". (like in the issue)
4. you should be able to find the item.

## Checklist

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [ESLint](https://eslint.org/) validation using `yarn lint`
- [x] My PR doesn't introduce circular dependencies (verified via `yarn check-circ-deps`)
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR fixes an issue ticket, I've [linked them together](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

### CODE REVIEW

**Comment by CrisGuzmanS** [comment]
Tim, i need to fix lint issues before

File: src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts [hunk 1]
```diff
@@ -122,19 +122,19 @@ export class BrowseByMetadataPageComponent implements OnInit, OnDestroy {
   fetchThumbnails: boolean;
 
   public constructor(protected route: ActivatedRoute,
-                     protected browseService: BrowseService,
-                     protected dsoService: DSpaceObjectDataService,
-                     protected paginationService: PaginationService,
-                     protected router: Router,
-                     @Inject(APP_CONFIG) public appConfig: AppConfig) {
+    protected browseService: BrowseService,
```
Comment (tdonohue) [inline src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts:125]: @CrisGuzmanS : Would it be possible to put the alignment back to how it was in these files?  It appears your IDE or editor has changed these files so that the parameters to methods are no longer aligned... It happened in all the methods of this file, so it was probably an automated change.  

But, it makes this PR appear much large then it actually is... plus, the code is harder to read when these params are no longer aligned.

Comment (CrisGuzmanS) [reply src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts]: @tdonohue for sure! al already did it 👍

**Comment by tdonohue** [comment]
@CrisGuzmanS : This now has some minor lint errors (cause of trailing spaces).  If you run `yarn lint` locally you should be able to find them...or look at the "Files changed" tab in this PR for where they appear.

**Comment by CrisGuzmanS** [comment]
I already fixed them @tdonohue 👍 my apologies.

**Review by artlowel — APPROVED** [review]
Thanks @CrisGuzmanS!
