### PR TITLE
Fix for PR#1822 - Adjusted two equality checks for scope type which always return false.

### LINKED ISSUE #1822: When using entities, metadata values with visibility set as “workflow” are not displayed in the UI during workflow.
**Describe the bug**
During workflow, after selecting an entity in a metadata (i.e dc.contributor.author) the value is not  displayed in the UI but the relation is effectivelly created. 

If the page is refreshed manually, the entity is displayed.  

This problem occurs if the metadata element on which the entity is configured in the submission-forms.xml with the visibility status “workflow” (as shown below). 
image

**To Reproduce**

1. Assign <visibility>workflow</visibility> to a metadata field (i.e dc.contributor.author). 
2. Log in as submitter and go to MyDSpace. 
3. Make a new submission in the collection in with previously metadata field has been configured. 
4. Log in as editor and go to MyDSpace and display workflow tasks. 
5. Assign yourself the newly made submission. 
image
6. On the metadata field clic on the magnifying glass buton.  
7. Select at least one value in the window and close the window. 

image

The values selected are not displayed on the page. 

Refresh the page, the values are displayed. 

**Expected behavior**
Trigger an automatic refresh of the form when value have been selected in the entity search page so that it is displayed. 
 
**Related work**
This problem may have been caused by the following patch introduced in 7.3: https://github.com/DSpace/dspace-angular/pull/1524

### PR DESCRIPTION
**Pull request by FelixNicol**
## References
* Fixes #1822

## Description
During workflow, after selecting an entity in a metadata (i.e dc.contributor.author) the value is not displayed in the UI but the relation is effectivelly created.

Currently there are two strict equality comparisions which always return false in section-form-component.ts when checking for submission scope. The patch allow proper comparision between values.

There are similar patches using boxing elsewere in the code. I think this is caused by the deserialisation of the response by angular which type submissionObject.type as string instead of an instance of the class «ResourceType». Casting submissionObject allow us to compare the strings.

A more robust solution would likely be to adjust how angular deserialise the response into a submissionObject. However it would also require some changes everywere similar patches where applied.

## Instructions for Reviewers
List of changes in this PR:
* Main fix is in section-form-component.ts. 
* Added workspaceitem.resource-type.ts and modified workspaceitem.model.ts for uniformity with other similar models.
* Modified unit test to check for value.

Complete guide for how to reproduce the bug is in the linked issue (#1822).

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [n/a] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [n/a] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

File: src/app/submission/sections/form/section-form.component.ts [hunk 1]
```diff
@@ -261,10 +261,10 @@ export class SubmissionSectionFormComponent extends SectionModelComponent {
 
     switch (scope) {
       case SubmissionScopeType.WorkspaceItem: {
-        return this.submissionObject.type === WorkspaceItem.type;
+        return (this.submissionObject as any).type === WorkspaceItem.type.value;
```
Comment (atarix83) [inline src/app/submission/sections/form/section-form.component.ts:264]: @FelixNicol 

shouldn't it be more like the following
``` 
(this.submissionObject as any).type.value === WorkspaceItem.type.value
```

or am i missing something ?

**Review by atarix83 — COMMENTED** [review]
thanks @FelixNicol 

I have a doubt that the current and your implemementation are working when the visibility is `submission`. have you tried ?

File: src/app/submission/sections/form/section-form.component.ts (hunk 1 above)
Comment (FelixNicol) [reply src/app/submission/sections/form/section-form.component.ts:264]: Hi @atarix83, 

Took me a while to understand the problem. The "type" in the submissionObject is unserialised as a String and not as a ResourceType. That is why the original equality comparison didnt work properly: 
image
              

If I use type.value on the left like you propose it will not work because we cannot do a .value on a string:
image


On the left we have a string and on the right we have a ResourceType. This will therefore always return false. Then if I just write "this.submissionObject.type === WorkspaceItem.type.value" Angular will not allow it, because of course it is the wrong type. 

So I used boxing (as any) and now Angular no longer infer "type" as a ResourceType.

We have similar patches elsewere too. For example; app-routing-paths.ts, remote-data-build.service.ts, delete-comcol-page.component.ts, form-builder.service.ts or section-form-operations.service.ts. 

When I tested the solution, I only tested the case with SubmissionScopeType.WorkflowItem but u guess it should be the same with WorkspaceItem.

Comment (FelixNicol) [reply src/app/submission/sections/form/section-form.component.ts:264]: Here's some more details from the vscode debugger. 

Spy of submissionObject where we see type is a string and not a ResourceType:
image

I added some line to spy the process:
image

And here's the result:
image

**Review by tdonohue — APPROVED** [review]
👍 @FelixNicol : I gave this a quick test today, and it works for me when the Entity field has `<visibility>workflow</visibility>`.   I was able to reproduce the original bug in #1822 , and this PR fixes it.  (In the process of testing this though, I discovered adding relationships is a bit slow right now, see #1874.  But, it does work if you are patient.)

I also looked into @atarix83 's question about whether this works for `<visibility>submission</visibility>` ... it appears though that `<visibility>submission</visibility>` doesn't work on the latest `main` at all.  It also doesn't work with this PR...so there's no change in that behavior.   Currently, if you set `<visibility>submission</visibility>` the field is entirely hidden.  I'll log a separate bug about that (created in #1875)

So, overall, this looks good to me & it fixes the issue it set out to fix.  

@atarix83 : could you verify that your prior feedback/questions have been addressed?
