### PR TITLE
Search/MyDSpace fixes

### LINKED ISSUE #1610: MyDSpace Status search facet doesn't update to reflect user changes to task status
**Describe the bug**
The "Status" search facet on MyDSpace (workflow configuration) doesn't update when a workflow Item's status is changed. 
The resulting mismatch is very noticeable when there are only a few workflow Items and could be confusing.

**To Reproduce**
1. Go to https://demo7.dspace.org/mydspace?configuration=workflow (& make sure at least one workflow Item exists)
2. Open the "Status" facet
   * The listed facets should correspond to the search results
4. Toggle the task's claimed/pooled status
   * **The "Status" facet will stay unchanged**

**Expected behavior**
The "Status" facet should reflect the changed state of workflow Items.

### LINKED ISSUE #1736: Issues with claimed items in MyDSpace
When an item is claimed in the workflow, the counter in the sidebar filter facet is not updated.

Before and after claiming the first item:
image
image

If the filter is clicked, sometimes the newly claimed item is listed in the results as expected, and sometimes it is not. It may also happen that also the previously claimed items are not listed even if the REST request returns them:
image
image
image

If the page is refreshed, all items will be listed:
image

If the item is returned to the pool, if the filter is clicked it may happen that the newly returned item is still listed among the claimed ones. Trying to return it to the pool will result in an error.

### LINKED ISSUE #1840: Mydspace filters are not updated when switching from workspace to workflow task
**Describe the bug**
In the mydspace page when switching from workspaceitem to workflowitem the filters are not updated properly. Indeed only filters that are in common between the two search configuration are refreshed, while filter present in only one configuration are not loaded during the switch

**To Reproduce**
1. login as admin user
2. open the mydspace page
3. switch show dropdown in order to list workflow tasks
4. see which filters are present in the sidebar
5. click F5 to refresh the page
6. at this point the filters should be different because are loaded properly

https://user-images.githubusercontent.com/2486489/191264027-d0051e6e-b07b-4b47-87fa-c7814a32d080.mp4

**Expected behavior**
Filter should be loaded/refreshed properly when switching search configuration

### PR DESCRIPTION
**Pull request by atarix83**
## References
* Fixes #1840
* Fixes #1736
* Fixes #1610

## Description
This PR fixes several issues present in the search/mydspace page

## Instructions for Reviewers
Check bugs are resolved following the instructions present in the mentioned issues

List of changes in this PR:
* Filters list is retrieved now in the parent search.component and passed down to children filters component
* when a claimed/pool task action is performed an event is catched by the search component in order to refresh the filter values count

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [x] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [x] My PR doesn't introduce circular dependencies
- [x] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [x] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by tdonohue** [comment]
@atarix83 : This now has merge conflicts. Could you rebase it when you get the chance?

**Review by tdonohue — CHANGES_REQUESTED** [review]
@atarix83 : The code here looks reasonable & seems to mostly work, but I've also found a rather severe bug.

First, I should note that I've run all tests in production mode (`yarn build:prod; yarn serve:ssr`).

SEVERE BUG (this may also exist on `main`):
* When I tried to reproduce #1840 when running in Production Mode, **the application crashes:**
    * Login and go to MyDSpace
    * Change "show" dropdown to "workflow tasks"
    * Click F5 (or reload in browser)
    * At this point the application crashes & I see this error on the command prompt where I was running `yarn serve:ssr`: `TypeError: Cannot read properties of undefined (reading 'payload')`
    * Because it has crashed the app, I have to restart the UI by running `yarn serve:ssr` again.
    * This bug appears specific to the "workflow" view in MyDSpace.  I can also crash the application just by typing this in my browser http://localhost:4000/mydspace?configuration=workflow.  However, if I browse to that same page, everything works. Maybe it's a bug in SSR?

Verified fixes:
* Verified that #1736 is fixed & is no longer reproducible
* Verified that #1610 is fixed & is no longer reproducible

**Comment by atarix83** [comment]
@tdonohue 

I've reproduced the same problem in the main branch when for any reason the workflow's submitter is not available. I've fixed it now, could you check? thanks

**Review by ybnd — CHANGES_REQUESTED** [review]
Confirmed that this solves all three issues now (in dev and prod mode), so functionally everything's good!

_____
Edit: at one point I saw the following error in the logs:
```
ERROR TypeError: l is undefined
    getName http://localhost:4000/main.732ce2808c421619.js:1
    ngOnInit http://localhost:4000/main.732ce2808c421619.js:1
```
Presumably this is happening in `DSONameService.getName()`.
Haven't been able to replicate this again on this branch (or the demo instance) so I'm not sure what to think of it.

**Review by tdonohue — APPROVED** [review]
👍 Thanks @atarix83 !  I've verified the previously reported "severe" bug is fixed, and that this PR solves all three of the bugs linked to in the description.

So, all my feedback has been addressed.  I think this can move forward as soon as @ybnd 's feedback above is addressed.

File: src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.ts [hunk 1]
```diff
@@ -58,4 +60,9 @@ export class ClaimedSearchResultListElementComponent extends SearchResultListEle
     this.workflowitemRD$ = this.dso.workflowitem as Observable<RemoteData<WorkflowItem>>;
   }
 
+  ngOnDestroy() {
+    // This ensures the object is removed from cache, when action is performed on task
+    this.objectCache.remove(this.dso._links.workflowitem.href);
```
[the remark this answers is not in the document]
Comment (atarix83) [reply src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.ts:82]: @ybnd 

unfortunately using the invalidateByHref have a side effect where all the search results are loaded after an action is performed. It's strange because it happens only the first time, I've tried to invastigate without success, so for the moment i'd leave the method as is if you agree. You can see the problem in the video below

https://user-images.githubusercontent.com/2486489/193040254-80c368b4-5fcb-4be8-bb50-10be2f3e96a4.mp4

File: src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts [hunk 2]
```diff
@@ -187,7 +187,10 @@ export class ListableObjectComponentLoaderComponent implements OnInit, OnChanges
           this.compRef.destroy();
           this.object = reloadedObject;
           this.instantiateComponent(reloadedObject);
-          this.contentChange.emit(reloadedObject);
+          // Add delay before emitting event to allow the new object is instantiated
+          setTimeout(() => {
```
[the remark this answers is not in the document]
Comment (atarix83) [reply src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts]: I realized the problem is not to wait for the new object is instantiated on angular side, but is due to the rest because solr indexes should be updated, so a bit delay is necessary before making the new request used to update filters count. I'm aware is not the best solution, i tried to optimize the code using a debounceTime operator instead of setTimeout

[the remark this answers is not in the document]
Comment (ybnd) [reply src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts]: `debounceTime` is better, but if this is related REST/Solr maybe this should be addressed in REST down the line?

e.g. if task action endpoints could await Solr reindex before responding this delay may no longer be required

File: src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (ybnd) [reply src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.ts:82]: Right, I made a bad call here: it makes sense that this uncaches all entries since invalidate goes after the whole request and not just the object

So it's fine as is, sorry about that.

Not sure why it would be different the second time around though.

File: src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (atarix83) [reply src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts]: @ybnd 

I found out the real problem, basically is a cache issue on angular side [here](https://github.com/4Science/dspace-angular/blob/CST-6876/src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts#L284)

What I've observed is the rest request return the response with the updated filter counts, but in the mentioned point I get the old response despite the fact when the filter should be reloaded I pass the `useCachedVersionIfAvailable` [flag to false](https://github.com/4Science/dspace-angular/blob/CST-6876/src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts#L120). For that I was thinking it was an issue on backend side. 
I can't figure it out why with the delay I get the updated response, do you have any suggestion?

[the remark this answers is not in the document]
Comment (ybnd) [reply src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts]: Looking at this more closely it does seem like there's a lot of nested subscriptions here ([one](https://github.com/DSpace/dspace-angular/pull/1845/files#diff-95b607c8c0460f6ff4f25cdd8806c88892ff1e93da313f4e228d37ac6675e6feR119), [two](https://github.com/DSpace/dspace-angular/pull/1845/files#diff-95b607c8c0460f6ff4f25cdd8806c88892ff1e93da313f4e228d37ac6675e6feR299), [three](https://github.com/DSpace/dspace-angular/pull/1845/files#diff-95b607c8c0460f6ff4f25cdd8806c88892ff1e93da313f4e228d37ac6675e6feR328))

IMO this is the first thing we should look at -- can you refactor this method (and other similar cases) until there's one subscription at most?

File: src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts [hunk 3]
```diff
@@ -110,66 +112,15 @@ export class SearchFacetFilterComponent implements OnInit, OnDestroy {
...
-                };
-              }
-            )
-          );
+    this.subs.push(
+      this.searchOptions$.subscribe(() => this.updateFilterValueList()),
+      this.refreshFilters.asObservable().pipe(
+        filter((toRefresh: boolean) => toRefresh),
+      ).subscribe(() => {
+        this.retrieveFilterValues(false);
```
Comment (ybnd) [inline src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts:120]: `retrieveFilterValues` shouldn't contain `subscribe`s if you need to use it here.

File: src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts [hunk 4]
```diff
@@ -324,6 +275,67 @@ export class SearchFacetFilterComponent implements OnInit, OnDestroy {
...
+                if (hasValue(fValue)) {
+                  return fValue;
+                }
+                const filterValue = stripOperatorFromFilterValue(value);
+                return Object.assign(new FacetValue(), { label: filterValue, value: filterValue });
+              });
+            })
+          );
+        })
+      ).subscribe((rd: RemoteData<PaginatedList<FacetValue>[]>) => {
```
Comment (ybnd) [inline src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts:328]: Nested `subscribe`

File: src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts [hunk 5]
```diff
@@ -324,6 +275,67 @@ export class SearchFacetFilterComponent implements OnInit, OnDestroy {
...
+                  page: page
+                };
+              }
+            )
+          );
+      })
+    );
+
+    let filterValues = [];
+    this.subs.push(facetValues$.subscribe((facetOutcome) => {
```
Comment (ybnd) [inline src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts:299]: This `subscribe` shouldn't be here if this method is called from another `subscribe`

File: src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts [hunk 6]
```diff
@@ -166,27 +165,32 @@ export class ListableObjectComponentLoaderComponent implements OnInit, OnChanges
...
+      (this.compRef.instance as any).reloadedObject.pipe(
+        // Add delay before emitting event to allow the new object is elaborated on REST side
+        debounceTime((100)),
+        take(1)
+      ).subscribe((reloadedObject: DSpaceObject) => {
         if (reloadedObject) {
           this.compRef.destroy();
           this.object = reloadedObject;
           this.instantiateComponent(reloadedObject);
+          this.cdr.detectChanges();
```
Comment (ybnd) [inline src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts:193]: What changed to make this call necessary now?
Please check if you can remove it again if you can get the caching issue fixed.

File: src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts [hunk 7]
```diff
@@ -324,6 +275,67 @@ export class SearchFacetFilterComponent implements OnInit, OnDestroy {
...
+              });
+            })
+          );
+        })
+      ).subscribe((rd: RemoteData<PaginatedList<FacetValue>[]>) => {
+        this.animationState = 'ready';
+        this.filterValues$.next(rd);
+
+      }));
+      this.subs.push(newValues$.pipe(take(1)).subscribe((rd) => {
```
Comment (ybnd) [inline src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts:333]: This `subscribe` shouldn't be here if this method is called from another `subscribe`

**Review by ybnd — CHANGES_REQUESTED** [review]
As mentioned in https://github.com/DSpace/dspace-angular/pull/1845#discussion_r984641016: on closer inspection there's a few parts that should to be refactored before we can look for potential lower-level caching issues.

File: src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (atarix83) [reply src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts]: @ybnd 

I've removed the nested subscriptions, I don't know why with a delay we get the [updated response here](https://github.com/4Science/dspace-angular/blob/CST-6876/src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts#L288)

File: src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts (hunk 3 above)
Comment (atarix83) [reply src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts]: done

File: src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts (hunk 4 above)
Comment (atarix83) [reply src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts]: done

File: src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts (hunk 5 above)
Comment (atarix83) [reply src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts]: done

File: src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts (hunk 7 above)
Comment (atarix83) [reply src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts]: done

File: src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts (hunk 6 above)
Comment (atarix83) [reply src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts:193]: this is neccessary otherwise sometimes new element does not appear immediatly, but after moving in the page. Anyway with or without the problem with cache persists

File: src/app/shared/search/search.component.ts [hunk 8]
```diff
@@ -332,6 +349,15 @@ export class SearchComponent implements OnInit {
     this.sidebarService.expand();
   }
 
+  /**
+   * Emit event to refresh filter content
+   * @param $event
+   */
+  public onContentChange($event: any) {
+    this.retrieveFilters(this.lastSearchOptions);
+    this.refreshFilters.next(true);
```
Comment (ybnd) [inline src/app/shared/search/search.component.ts:358]: IMO it's most likely that the issue with filter facets not refreshing starts somewhere in this component, and isn't directly related to dynamic loading.

I thought we could address it by pushing to `refreshFilters` within the subscription in `retrieveFilters` but this isn't sufficient.

File: src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts [hunk 9]
```diff
@@ -110,66 +116,14 @@ export class SearchFacetFilterComponent implements OnInit, OnDestroy {
...
-                  values: observableOf(results),
-                  page: page
-                };
-              }
-            )
-          );
-      })
+    this.subs.push(
+      this.searchOptions$.subscribe(() => this.updateFilterValueList()),
+      this.refreshFilters.asObservable().pipe(
```
Comment (ybnd) [inline src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts:121]: If we can't find a better solution than the delay, I think we should at least move it to this pipe instead of the `ListableObjectComponentLoaderComponent`. Otherwise we'd be affecting a lot of other components.

I checked this locally real quick and it seems to have the same effect if we move the `debounceTime` here and leave out the `detectChanges` call.

**Review by ybnd — CHANGES_REQUESTED** [review]
Haven't been able to find the cause of the delay but in the worst case we can do this as a temporary fix instead of modifying the listable object loader

**Comment by ybnd** [comment]
@tdonohue earlier, @artlowel looked this over to see if we could get rid of the `debounceTime` altogether (by using `zone.runOutsideAngular` but this wasn't successful.

In other words it seems like `debouceTime` is our best option on short notice.

@atarix83 can you still remove the new `detectChanges` call though?
Once that's done I'll sign off

**Review by tdonohue — CHANGES_REQUESTED** [review]
@atarix83 :  Retested today, and while most of the fixes still work, I think the fix for #1736 has an issue now.  When clicking either "claim" or "return to pool", I'm finding the **title** of the item disappears until I reload the page.

Here's an example of an Item that I've currently claimed.  I've circled the title:
before-pool

Here's what it looks like after I click "Return to pool".  Title is gone & Submitter is also gone.
After-click

If I click reload in my browser, the missing information is back.  Here's what it looks like:
After-reload

I did all this testing in production mode (`yarn build:prod; yarn serve:ssr`).  Beyond this odd reload issue, the rest seems to be working.  I believe this all worked previously, but a recent refactor must have broken it.

File: src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts (hunk 6 above)
Comment (ybnd) [reply src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts:191]: Have you checked whether this is still the case after the refactor yesterday?
When I tested with `debounceTime` in the facet component locally, it seemed that this call was no longer required here.

**Comment by atarix83** [comment]
@tdonohue  @ybnd 

I investigated after the issue [reported by Tim](https://github.com/DSpace/dspace-angular/pull/1845#pullrequestreview-1129088122). The problem was the same already [reported by Yury](https://github.com/DSpace/dspace-angular/pull/1845#pullrequestreview-1123456607) and I found out the instability of the process was due to the fact there were a bunch of components related to the workflow-actions that retrieved workflowitem and item objects with new observable every time. So I decided to refactor in order to pass down the objects already available in the search element component down to the workflowaction components. So apart from the workaround with the delay the result is that now it works very smoothly. Please have a look again.


@ybnd 
I'd leave the [detect change](https://github.com/4Science/dspace-angular/blob/CST-6876/src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts#L191) because it makes the transition between states more fluid. Moreover this has impact only with workflow task search element.
You can verify the result in the following videos. First one is with detect change the second one without


https://user-images.githubusercontent.com/2486489/193830385-1b62f62d-30d5-483e-83fd-ef7c29353e4c.mp4




https://user-images.githubusercontent.com/2486489/193830529-65fb9f72-1c80-4394-aaae-4edf3ad68c01.mp4

**Comment by tdonohue** [comment]
@atarix83 : Overall, this looks good now & the title bug is fixed. But I notice the "Submitter" listing still disappears when you either claim a task or return it to the pool.  
* You can see that behavior in your **first** video above (when you click claim on the second item in the list, the "Submitter" disappears).
* However, I notice in your **second** video above that same problem no longer occurs.  The "Submitter" tag always appears even after reload.

Overall, I'm +1 this change as it's much better than `main`.  But, I wanted to report the "Submitter" display issue in case you see another quick fix.

**Comment by ybnd** [comment]
@atarix83 thank you for these examples, I hadn't caught this nuance before!

+1

**Review by ybnd — APPROVED** [review]

**Comment by atarix83** [comment]
@tdonohue 

it should be fixed now, could you check? thanks

**Review by tdonohue — APPROVED** [review]
👍 Thanks @atarix83 !  I can verify that the prior bugs are now all fixed and I'm not finding any other obvious bugs.
